<div class="container">
    <div class="row">
		<div class="">  
			<form method="POST" action="/atn/autorizacion/formvalidation?strInput=<?php echo $this->data['ID_CITA']?>" id="FormData" class="form-horizontal ">
				<input type="hidden" id="optReg" name="optReg"  value="sendForm"/>     
				<input type="hidden" id="strInput" name="strInput"  value="<?php echo $this->data['ID_CITA']?>"/>				
				<input type="hidden" id="inputFormulario" name="inputFormulario"  value="<?php echo $this->idFormulario;?>"/>
				<input type="hidden" id="inputFecha"      name="inputFecha"  value="<?php echo $this->fechaInicio;?>"/>
	        	<div style="height: 450px; overflow-y: auto; overflow-x: hidden;">
		        	<?php foreach($this->aElements as $key => $items):?>
		        		<?php if($items['ID_TIPO']=='8'):?>
		        			<span class="span12 text-center"><h4><?php echo $items['N_ELEMENTO'];?></h4></span>
		        		<?php elseif($items['ID_TIPO']=='3' || $items['ID_TIPO']=='2'):?>
							<div class="control-group">
								<label class="span4 text-right"> <span class="required">*</span> <?php echo $items['N_ELEMENTO'];?> &nbsp;</label>
								<div class="controls">
									<?php echo @$items['INPUT'];?>	
								</div>
							</div>
						<?php endif;?>
		        	<?php endforeach;?>	        		
	        	</div>
	        	<div class="span12">
	        		<div class="span6 no-margin text-center">
	        			-<button type="submit" class="btn btn-primary">Guardar Validación</button>
	        		</div>
	        		<div class="span6 no-margin text-center">
	        			<button type="button" onClick="parent.closeDetail();" class="btn btn-default">Cancelar Validación</button>
	        		</div>
	        	</div>	        	
        	</form>
        </div>
    </div>
</div>
<?php $this->headScript()->captureStart() ?>
    $().ready(function(){
    console.log("pasa algo");
		$("#FormData").validate({
		    rules: {
	        <?php foreach($this->aElements as $key => $items):?>
	        <?php if($items['REQUERIDO']=='S' || $items['ID_TIPO']==2 || $items['ID_TIPO']==3 ):?>
	        	input_<?php echo $items['ID_ELEMENTO'];?>: "required",
	    	<?php endif;?>
	    	<?php endforeach;?>
		    },
		    messages: {
	        <?php foreach($this->aElements as $key => $items):?>
	        <?php if($items['REQUERIDO']=='S' || $items['ID_TIPO']==2 || $items['ID_TIPO']==3 ):?>
	        	input_<?php echo $items['ID_ELEMENTO'];?>: "Campo Requerido",
	    	<?php endif;?>
	    	<?php endforeach;?>
		    },
		    
		    submitHandler: function(form) {
		        form.submit();
		    }
		}); 


    });
<?php $this->headScript()->captureEnd() ?>