<?php $this->headScript()->appendFile('/js/modules/leasing/validateUnits.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/leasing/units/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información de la Unidad</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/leasing/units/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>					
			                <fieldset>
			                    <div id="errorMsg" class="alert alert-error hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Alguno de los datos estan incorrectos,favor de verificarlos.
			                    </div>
			                    <div class="alert alert-success hide">
			                        <button class="close" data-dismiss="alert"></button>
			                        Datos correctos
			                    </div>
                                <div class="control-group">
                                    <label class="control-label">Marca<span class="required">*</span></label>
                                    <div class="controls">
                                        <select class="span4 m-wrap" name="inputMarca" id="inputMarca" <?php echo $disabled;?>  onChange="getoptionsCbo('Modelo','modeloa',this.value,'','');">
                                            <option value="">Seleccionar una opción</option>
                                            <?php echo $this->aMarcas;?>
                                        </select>
                                    </div>
                                </div>  
                                <div class="control-group">
                                    <label class="control-label">Modelo<span class="required">*</span></label>
                                    <div class="controls">
                                        <div id="divModelo">
                                            <select class="span4 m-wrap" name="inputModelo" id="inputModelo" <?php echo $disabled;?> >
                                                <option value="">Seleccionar una opción</option>
                                                <?php echo $this->aModelos;?>
                                            </select>
                                        </div>
                                    </div>
                                </div>			                    
								<div class="control-group">
									<label class="control-label">Color<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputColor" <?php echo $disabled;?> >
											<?php echo $this->sColores; ?>
										</select>
									</div>
								</div>	
								<div class="control-group">
									<label class="control-label">Año<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputAnio" <?php echo $disabled;?> >
											<?php echo $this->sAnios; ?>
										</select>
									</div>
								</div>								
								<div class="control-group">
									<label class="control-label">VIN<span class="required">*</span></label>
									<div class="controls">
										<input type="text" name="inputEco" data-required="1" class="span6 m-wrap upperClass" value="<?php echo @$this->data['ECONOMICO']; ?>"  <?php echo $disabled;?> >
									</div>
								</div>								
								<div class="control-group">
									<label class="control-label">Placas<span class="required">*</span></label>
									<div class="controls">
										<input name="inputPlacas" type="text" class="span6 m-wrap upperClass" value="<?php echo @$this->data['PLACAS']; ?>" <?php echo $disabled;?> >
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">No. serie<span class="required">*</span></label>
									<div class="controls">
										<input name="inputIden" type="text" class="span6 m-wrap upperClass" value="<?php echo @$this->data['IDENTIFICADOR']; ?>" <?php echo $disabled;?> >
									</div>
								</div>

								<!--
								<div class="control-group">
									<label class="control-label">Identificador 2<span class="required">*</span></label>
									<div class="controls">
										<input name="inputIden2" type="text" class="span6 m-wrap upperClass" value="<?php echo @$this->data['IDENTIFICADOR_2']; ?>" <?php echo $disabled;?> >
									</div>
								</div>	-->
								<!--
								<div class="control-group">
									<label class="control-label">Tipo Equipo<span class="required">*</span></label>
									<div class="controls">
										<input name="inputEquipo" type="text" class="span6 m-wrap upperClass" value="<?php echo @$this->data['TIPO_EQUIPO']; ?>" <?php echo $disabled;?> >
									</div>
								</div>	
								<div class="control-group">
									<label class="control-label">Tipo Vehículo<span class="required">*</span></label>
									<div class="controls">
										<input name="inputVehiculo" type="text" class="span6 m-wrap upperClass" value="<?php echo @$this->data['TIPO_VEHICULO']; ?>" <?php echo $disabled;?> >
									</div>
								</div>	
								-->
																															
								<div class="control-group">
									<label class="control-label">Estatus<span class="required">*</span></label>
									<div class="controls">
										<select class="span6 m-wrap" name="inputStatus" <?php echo $disabled;?> >
											<?php echo $this->status; ?>
										</select>
									</div>
								</div>
								<?php if($disabled!='disabled'):?>
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Guardar</button>
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>
								</div>
								<?php endif;?>
						</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  