<!DOCTYPE html>
<html lang="es" class="no-js">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Siames</title>
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />   
    <link type="image/x-icon" href="/siames/image/favicon.ico" rel="shortcut icon">
    <!-- Bootstrap -->
        <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link href="/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
        <link href="/assets/styles.css" rel="stylesheet" media="screen"> 
        <link href="/assets/DT_bootstrap.css" rel="stylesheet" media="screen">
        
        <link rel="stylesheet" href="/css/datepicker.css">
        <link rel="stylesheet" href="/vendors/graphs/css/jquery.circliful.css">

        <link href="/vendors/uniform.default.css" rel="stylesheet" media="screen">
        <link href="/css/cmxform.css" rel="stylesheet" media="screen">
        <link href="/vendors/wysiwyg/bootstrap-wysihtml5.css" rel="stylesheet" media="screen">      
        <link href="/vendors/chosen.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
        <link href="/vendors/fullcalendar/fullcalendar.css" rel="stylesheet" media="screen">  
        <link href="/css/slider.css" rel="stylesheet" media="screen">        
        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    
    <body class="body-all">
        <?php echo $this->render('header.phtml', 
                                  array (
                                    'menu'          => $this->menu,
                                    'bUserContact'  => @$this->bUserContact
                                  )); ?>   
        <div class="container-fluid">
            <div class="row-fluid">  
                <?php echo $this->render('menu.phtml', 
                                          array (
                                            'dataUser'    => $this->dataUser,
                                            'modules'     => $this->modules                 
                                          )); ?>
                <div class="<?php echo (@$this->dataUser['allwindow']) ? 'span12': 'span9';?>" id="content">
                    <div class="row-fluid">
                        <?php echo $this->layout()->content; ?>
                    </div>
                </div>        
            </div>
        </div>

        <!-- Modal -->

        <!--
        <div class="modal fade hide" id="myModalRecovery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display:none;">
          <div class="modal-dialog modal-sm">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Cambiar mi Contraseña</h4>
              </div>
              <div class="modal-body i-body">             
                <iframe class="hmodal280" id="iFrameModalRec" src="/main/main/recovery" style="zoom:0" frameborder="0"></iframe>
              </div>
            </div>
          </div>
        </div>      
    -->  

        <script src="/vendors/jquery-1.9.1.min.js"></script>
        <script src="/bootstrap/js/bootstrap.min.js"></script>
        <script src="/vendors/datatables/js/jquery.dataTables.min.js"></script>
        <script src="/assets/scripts.js"></script>
        <script src="/assets/DT_bootstrap.js"></script> 

        <script src="/vendors/jquery.uniform.min.js"></script>
        <script src="/vendors/chosen.jquery.min.js"></script>
        <script src="/js/bootstrap-datepicker.js"></script>  
        <script src="/vendors/wysiwyg/wysihtml5-0.3.0.js"></script>
        <script src="/vendors/wysiwyg/bootstrap-wysihtml5.js"></script>
        <script src="/vendors/wizard/jquery.bootstrap.wizard.min.js"></script>
        <script type="text/javascript" src="/vendors/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="/assets/form-validation.js"></script>   
        <script src="/js/modules/functionGral.js"></script>   
        <script src="/js/bootstrap-datetimepicker.min.js"></script>          
      <?php echo $this->headLink() ?>
      <?php echo $this->headStyle() ?>
      <?php echo $this->headScript() ?>      
    </body>

</html>