<!DOCTYPE html>
<html lang="es" class="no-js">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Siames</title>
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />   
    <link type="image/x-icon" href="/siames/image/favicon.ico" rel="shortcut icon">
    <!-- Bootstrap -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="/vendors/easypiechart/jquery.easy-pie-chart.css" rel="stylesheet" media="screen">
    <link href="/assets/styles.css" rel="stylesheet" media="screen">
    <link href="/assets/DT_bootstrap.css" rel="stylesheet" media="screen">        
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="/css/datepicker.css" rel="stylesheet" media="screen">
    <link href="/vendors/uniform.default.css" rel="stylesheet" media="screen">
    <link href="/vendors/chosen.min.css" rel="stylesheet" media="screen">   
    <link href="/css/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">
    </head>    
    <body class="bg-white">
        <?php echo $this->layout()->content; ?>
      <script src="/vendors/jquery-1.9.1.min.js"></script>
      <script src="/bootstrap/js/bootstrap.min.js"></script>
      <script src="/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
      <script src="/vendors/datatables/js/jquery.dataTables.min.js"></script>      
      <script src="/assets/DT_bootstrap.js"></script>      
      <script src="/vendors/jquery.uniform.min.js"></script>
      <script src="/vendors/chosen.jquery.min.js"></script>
      <script src="/js/bootstrap-datepicker.js"></script>      
      <script src="/vendors/easypiechart/jquery.easy-pie-chart.js"></script>
      <script src="/vendors/jquery-validation/dist/jquery.validate.min.js"  type="text/javascript" ></script>
      <script src="/assets/form-validation.js"></script>
      <script src="/vendors/jquery.knob.js"></script>
      <script src="/vendors/raphael-min.js"></script>
      <script src="/vendors/morris/morris.min.js"></script>                  
      <script src="/assets/scripts.js"></script>
      <script src="/js/modules/functionGral.js"></script>  
        <script src="/js/bootstrap-datetimepicker.min.js"></script>         
      <?php echo $this->headLink() ?>
      <?php echo $this->headStyle() ?>
      <?php echo $this->headScript() ?>      
    </body>

</html>