<div class="span3" id="sidebar" style="display:<?php echo (@$this->dataUser['allwindow']) ? 'none': 'block';?>">
    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
        <?php foreach($this->modules as $key => $items): ?> 
            <?php if($items['IDMENU']==@$this->moduleInfo["ID_MENU"]): ?>
            <li class="<?php echo ($items['ID_MODULO']==@$this->moduleInfo["ID_MODULO"]) ?'active':'';?>">
                <a href="<?php echo $items['S_MODULE'];?>"><i class="icon-chevron-right active"></i> <?php echo $items['M_DESCRIPCION'];?></a>
            </li>            
            <?php endif;?>
        <?php endforeach;?>
    </ul>
</div>