<?php $this->headScript()->appendFile('/js/dataTables.tableTools.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/dataTables.tableTools.css');?>
<?php $this->headScript()->appendFile('/js/jQuery.print.js'); ?>
<?php $this->headScript()->appendFile('/js/atn/jsTiempos.js'); ?>
<div id="divDataPersonal" class="hide"><?php foreach($this->aTecnicos as $key => $items):?><?php echo ($control==0) ? '': '?';?><?php echo $items['ID']."|".$items['NAME']."|".$items['ID_SUCURSAL'];?><?php $control++;?><?php endforeach;?>
</div>
<div class="row panel-data formcustom">
    <div class="span12">    
        <div class="block no-margin-l">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Reporte de Tiempos</div>
            </div>
            <div class="block-content-min collapse in">
                <div class="span12">
                        <form method="POST" action="/atn/reptiempos/index" id="FormData" class="form-horizontal formcustom">
                            <input type="hidden" name="optReg" value="search" />
                            <input type="hidden" name="inputStatus" id="inputStatus" value="<?php echo $this->iStatus; ?>" />
                            <fieldset> 
                                <div class="span12">   
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Buscar Por<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="chzn-select" id="cboTypeSearch" name="cboTypeSearch" onChange="getReport()">
                                                    <?php echo $this->aTypeSearchs;?>
                                                </select>
                                            </div>
                                        </div>   
                                    </div>
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Fecha Inicio<span class="required">*</span></label>
                                            <div class="controls">
                                                <input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputFechaIn']; ?>">
                                            </div>
                                        </div>   
                                    </div>
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label">Fecha Fin<span class="required">*</span></label>
                                            <div class="controls">
                                                <input readonly type="text" id="inputFechaFin" name="inputFechaFin" class="m-wrap" value="<?php echo (@$this->data['inputFechaFin']); ?>">                          
                                            </div>
                                        </div>                                      
                                    </div>    
                                </div>  
                                <div class="span12 no-margin-l">
                                    <div class="span4">       
                                        <div class="control-group">
                                            <label class="control-label">Sucursales<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="chzn-select" id="cboInstalacion" name="cboInstalacion" onChange="getReport()">
                                                    <option value="">Todos</option>
                                                    <?php echo $this->cInstalaciones;?>
                                                </select>
                                            </div>
                                        </div>                                          
                                    </div>
                                    <div class="span4 <?php echo (isset($this->showUsers))? '': 'hide'; ?>">
                                        <div class="control-group">
                                            <label class="control-label">Técnicos<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="chzn-select" id="inputTecnicos" name="inputTecnicos" >
                                                    <option value="">Todos</option>
                                                    <?php echo $this->aTecnicos;?>
                                                </select>
                                            </div>
                                        </div>                          
                                    </div>
                                    <div class="span4">
                                        <div class="control-group">
                                            <label class="control-label"></label>
                                            <div class="controls">
                                                <button type="submit" class="btn row-margin-r5 btn-primary">Buscar</button>
                                            </div>
                                        </div>
                                    </div> 
                                </div>                          
                            </fieldset>
                        </form>
                </div>
                <div class="row row-margin-left25 ">
                    <div class="">
                        <?php if(count($this->aResume)>0): ?>
                            <div class="btn-group">
                             <a href="javascript:getReportAll()"><button class="btn btn-success"> Exportar <i class="icon-file icon-white"></i></button></a>                                    
                            </div>
                             <!--<div class="btn-group">
                                <button onClick="printPage()" class="btn btn-primary"> Imprimir <i class="icon-print icon-white"></i></button>
                            </div>-->
                        <?php endif;?>
                    </div>                        
                    <table cellspacing="0" width="100%" class="table table-striped table-bordered display"  id="dataTable">
                        <thead>             
                            <tr>
                                <th>Folio Cita</th>
                                <th>Tipo Servicio</th>
                                <th class="text-center" style="width:80px;"> Técnico Asignado</th>
                                <th class="text-center" style="width:70px;"> Inicio Cita</th>                                
                                <th class="text-center" style="width:70px;"> Fin Cita</th>
                                <th>Duración cita (mins.)</th><!-- Inicio-Fin cita-->
                                <th>Arribo (mins.)</th> <!--programada - arribo-->
                                <th>Diferencia inicio cita (mins.)</th> <!--Programada - Inicio real-->
                                <th>Recepción Unidad (mins.)</th>
                                <th>Instalación (mins.)</th>
                                <th>Pruebas y Validación (mins.)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $result = '';$print=false?>
                            <?php foreach($this->aResume as $key => $items): ?>
                                <?php $print = (isset($this->iStatus) && $this->iStatus != -1) ? (($this->iStatus==$items['IDE']) ? true : false) : true; ?>
                                <?php if($print):?>
                                    <tr>
                                        <td><?php echo $items['FOLIO'];?></td>
                                        <td><?php echo $items['N_TIPO'];?></td>
                                        <td><?php echo $items['NOMBRE_TECNICO'];?></td>    
                                        <td><?php echo $items['FECHA_INICIO'];?></td>  
                                        <td><?php echo $items['FECHA_TERMINO'];?></td>  
                                        <td><?php echo $items['DIF_FIN'];?></td> 
                                        <td><?php echo $items['DIF_ARRIBO'];?></td> 
                                        <td><?php echo $items['DIF_INICIO'];?></td> 
                                        <td><?php echo @$items['FECHA_RECEPCION_UNIDAD']['DIF_CAPTURA'];?></td> 
                                        <td><?php echo @$items['FECHA_INICIO_INSTALACION']['DIF_CAPTURA'];?></td> 
                                        <td><?php echo @$items['FECHA_PRUEBAS']['DIF_CAPTURA'];?></td>   
                                    </tr>  
                                <?php endif;?>
                            <?php  endforeach;?>
                        </tbody>
                    </table>                                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade hide modal-lg" id="myModalinfoVis" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" ></h4>
        </div>
      <div class="modal-form i-body"> 
        <img id="loader" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>            
        <iframe class="hmodal500" id="iFrameDetCita" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>  