<?php $this->headScript()->appendFile('/js/modules/gralTables.js'); ?>
<div class="row panel-data">

    <input id="hRefLinkEdit" type="hidden" value="/messages/main?catId=" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Difusión de Mensajes</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                        <div class="table-toolbar">
                          <div class="btn-group">
                             <a href="/messages/main/getinfo?catId=-1"><button class="btn btn-success"> Nuevo mensaje <i class="icon-plus icon-white"></i></button></a>
                          </div>
                        </div>                      
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Estatus</th>
                                <th>Motivo</th>
                                <th>Enviar a</th>
                                <th>Fecha envio</th>
                                <th>Tipo de envio</th>                                
                                <th class="col-xs-2 col-md-2">
                                    Opciones
                                </th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php $control = 1;?>              
                            <?php foreach($this->aDatatable as $key => $items):?>
                                <tr>
                                    <td><?php echo $control;?></td>
                                    <td><?php echo $items['N_ESTATUS'];?></td>
                                    <td><?php echo $items['N_MOTIVO'];?></td>
                                    <td><?php echo $items['ENVIAR_A'];?></td>
                                    <td><?php echo $items['FECHA_ENVIAR'];?></td>
                                    <td><?php echo $items['REENVIO'];?></td>
                                    <td>
                                        <a href="/messages/main/getinfo?catId=<?php echo $items['ID_MENSAJE']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>  
                                    </td>
                                </tr>
                                <?php $control++;?>
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>