<?php $this->headScript()->appendFile('/vendors/graphs/js/jquery.circliful.js'); ?>
<?php $this->headScript()->appendFile('/js/info/jsValidateServices.js'); ?>

<input name="catId" type="hidden" value="<?php echo @$this->aCompany['ID_EMPRESA'];?>"/>
<div class="row panel-data formcustom">
    <div class="span12">    
        <div class="block no-margin-l no-margin-t">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                	<a href="javascript:window.history.back();"><i class="icon-circle-arrow-left fa-1"></i> Regresar</a>
                	<b><?php echo @$this->aCompany['NOMBRE'];?></b>
                </div>
            </div>
            <div class="block-content-min collapse in">
			    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
			    	<!--<li class="active"><a href="#tdates" data-toggle="tab">Citas</a></li>-->
			    	<li class="active"><a href="#tsolicitudes" data-toggle="tab">Solicitud Citas</a></li>
			        <li><a href="#tclientes" data-toggle="tab">Clientes</a></li>
					<li><a href="#tunidades" data-toggle="tab">Unidades</a></li>
					<li><a href="#tplaces" data-toggle="tab">Lugares</a></li>
					<li><a href="#tusuario" data-toggle="tab">Usuarios</a></li>
			    </ul>	

			    <div id="my-tab-content" class="tab-content bg-white">			        
			        <div class="tab-pane active" id="tsolicitudes">  
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTableSolic">
	                        <thead>
	                            <tr>
	                                <th>Cliente</th>
	                                <th>Tipo</th>                                        
	                                <th>Fecha</th>
	                                <th>Horario</th>
	                                <th>Tipo Equipo</th>
	                                <th>Unidad</th>                                        
	                                <th>Lugar</th>                                        
	                                <th>Estatus</th>
	                                <!--<th></th>-->
	                            </tr>
	                        </thead>
	                        <tbody>                                
	                            <?php foreach($this->aDataSolicitudes as $key => $items): ?>  
	                            <tr class="odd gradeX">
	                                <td><?php echo $items['N_EMP_CLIENTE']; ?></td>
	                                <td><?php echo $items['N_TIPO']; ?></td>
	                                <td><?php echo $items['FECHA_CITA']; ?></td>
	                                <td><?php echo $items['N_HORARIO']; ?></td>
	                                <td><?php echo $items['N_TEQUIPO']; ?></td>
	                                <td><?php echo $items['N_UNIDAD']; ?></td>
	                                <td><?php echo $items['N_SUCURSAL'];?></td>
	                                <td><?php echo $items['N_ESTATUS']; ?></td>
	                                <!--
	                                <td class="text-center">
	                                    <a href="/leasing/request/getinfo?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
	                                </td>-->
	                            </tr>    
	                            <?php endforeach;?>
	                        </tbody>
	                    </table>			        	
			        </div>			        
			        <div class="tab-pane " id="tclientes">  
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTableClients">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Razón Social</th>
                                    <th>RFC</th>
                                    <th class="span2 text-center">Estatus</th>
                                    <!--<th class="span2 text-center">Opciones</th>-->
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach(@$this->aDataClientes as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['NOMBRE']; ?></td>
                                    <td><?php echo $items['RAZON_SOCIAL']; ?></td>
                                    <td><?php echo $items['RFC']; ?></td>
                                    <td class="text-center"><?php echo ($items['ESTATUS']==1)      ? 'Activo': 'Inactivo'; ?></td>
                                    <!--<td class="text-center">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/leasing/clients/getinfo?catId=<?php echo $items['ID_EMP_CLIENTE']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        <?php endif;?>                                         
                                    </td>-->
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>			        	
			        </div>
			        <div class="tab-pane " id="tunidades">  
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTableUnits">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>VIN</th>
                                    <th>Placas</th>
                                    <th>Modelo</th>
                                    <th>No. Serie</th>
                                    <!--<th>Opciones</th>-->
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->aDataUnidades as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['N_CLIENTE']; ?></td>
                                    <td><?php echo $items['ECONOMICO']; ?></td>
                                    <td><?php echo $items['PLACAS']; ?></td>
                                    <td><?php echo $items['ANIO']; ?></td>
                                    <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                    <!--
                                    <td class="text-center">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/leasing/units/getinfo?catId=<?php echo $items['ID_UNIDAD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        <?php endif;?> 
                                        <?php if($this->dataUser['ELIMINAR']==1): ?>
                                            <a href="javascript:confirmDelete('<?php echo $items['ID_UNIDAD']; ?>')"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>
                                        <?php endif;?>
                                    </td>-->
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>			        	
			        </div>
			        <div class="tab-pane " id="tplaces">  
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTablePlaces">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Descripción</th>                           
                                    <th class="span2 text-center">Estatus</th>
                                    <!--<th class="span2 text-center">Opciones</th>  -->                                  
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->aDataPlaces as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['N_CLIENTE']; ?></td>
                                    <td><?php echo $items['DESCRIPCION']; ?></td>
                                    <td class="text-center"><?php echo ($items['ESTATUS']==1)      ? 'Activo': 'Inactivo'; ?></td>
                                    <!--
                                    <td class="text-center">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/leasing/branches/getinfo?catId=<?php echo $items['ID_SUCURSAL']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        <?php endif;?> 
                                        <?php if($this->dataUser['ELIMINAR']==1): ?>
                                            <a href="javascript:confirmDelete('<?php echo $items['ID_SUCURSAL']; ?>')"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>
                                        <?php endif;?>
                                    </td>-->
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>			        	
			        </div>
			        <div class="tab-pane " id="tusuario">  
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTableUsers">
                            <thead>
                                <tr>                                        
                                    <th>Nombre</th>
                                    <th>Perfil</th>
                                    <th>Usuario</th>
                                    <th>E-mail</th>
                                    <th>Estatus</th>
                                    <th>Operaciones</th>
                                    <th>Tel. Asignado</th>
                                    <!--<th></th>-->
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->aDataUsers as $key => $items): ?>  
                                <tr class="odd gradeX">                                        
                                    <td><?php echo $items['NOMBRE']; ?></td>
                                    <td><?php echo $items['PERFIL']; ?></td>
                                    <td><?php echo $items['USUARIO']; ?></td>
                                    <td><?php echo $items['EMAIL']; ?></td> 
                                    <td class="text-center"><?php echo ($items['ACTIVO']==1)?'Activo':'Inactivo'; ?></td>
                                    <td class="text-center"><?php echo ($items['FLAG_OPERACIONES']==1)?'Si':'No'; ?></td>
                                    <td><?php echo $items['N_IMEI']; ?></td>
                                    <!--
                                    <td class="text-center">
                                        <?php if($this->dataUser['LECTURA']==1): ?>
                                            <a href="/main/users/getinfo?catId=<?php echo $items['ID_USUARIO']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>
                                        <?php endif;?> 
                                        <?php if($this->dataUser['ELIMINAR']==1): ?>
                                            <a href="javascript:confirmDelete('<?php echo $items['ID_USUARIO']; ?>')"><button class="btn btn-danger"> <i class="icon-trash icon-white"></i></button></a>
                                        <?php endif;?>
                                    </td>-->
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>			        	
			        </div>			        			        
				</div>			    
			</div>
		</div>
	</div>
</div>