<?php $this->headScript()->appendFile('/js/companies/validateCompanies.js') ?>   
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/admin/companies/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información de la Arrendadora</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/admin/companies/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                <?php if(count(@$this->errors)>0):?>
		                    <?php if(@$this->errors['eEmpresa']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>La empresa ya se encuentra registrada, pongase en contacto con su administrador para crear su cuenta.</div>
								</div>		
		                    <?php elseif(@$this->errors['eUsuario']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>El usuario ya se encuentra registrado, favor de verificarlo.</div>
								</div>		                    							                    
		                    <?php elseif(@$this->errors['status']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>Ocurrio un error en el registro, favor de intentarlo mas tarde.</div>
								</div>
		                    <?php endif;?>    
		                <?php endif; ?>    
		                	<fieldset>
	                				<div class="span12 no-margin-left">
				                		<div class="span12">
											<div class="control-group">
												<label class="control-label">Nombre<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputDescripcion" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['NOMBRE']; ?>" >
												</div>
											</div>	
				                		</div>
				                	</div>

	                				<div class="span12 no-margin-left">
				                		<div class="span12">
				                			<div class="control-group">
												<label class="control-label">Razón Social<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputRazonSocial" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['RAZON_SOCIAL']; ?>" >
												</div>
											</div>	
				                		</div>
				                	</div>	
				                	
	                				<div class="span12 no-margin-left">
				                		<div class="span12">
				                			<div class="control-group">
												<label class="control-label">RFC<span class="required">*</span></label>
												<div class="controls">
												  <input name="inputRFC" type="text" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['RFC']; ?>" >
												</div>
											</div>	
				                		</div>
				                	</div>		


				                	<?php if($this->idToUpdate==-1): ?>

				                	<div class="span12 no-margin-left">
				                		<div class="span12">
											<div class="control-group">
												<label class="control-label">Dirección<span class="required">*</span></label>
												<div class="controls">
													<input name="inputDireccion" type="text" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['DIRECCION']; ?>" >
												</div>
											</div>
				                		</div>
				                	</div>

				                	<div class="span12 no-margin-left">
				                		<div class="span4">
											<div class="control-group">
												<label class="control-label">Tel. Fijo:<span class="required">*</span></label>
												<div class="controls">
												  <input name="inputTelFijo" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['TEL_FIJO']; ?>">
												</div>
											</div>	
				                		</div>
				                		<div class="span4">
											<div class="control-group">
												<label class="control-label">Tel. Móvil:<span class="required"></span></label>
												<div class="controls">
												  <input name="inputTelMovil" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['TEL_MOVIL']; ?>">
												</div>
											</div>
				                		</div>
				                		<div class="span4">
											<div class="control-group">
												<label class="control-label">Radio:<span class="required"></span></label>
												<div class="controls">
												  <input name="inputRadio" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['RADIO']; ?>">
												</div>
											</div>			                			
				                		</div>			                		
				                	</div>

				                	<?php endif;?>
									<!--
				                	<div class="span12 no-margin-left">
				                		<div class="span4">
											<div class="control-group">
												<label class="control-label">Cliente Ovision:<span class="required">*</span></label>
												<div class="controls">												
													<select class="span6 m-wrap"  autocomplete="off" id="inputClienteUDA" name="inputClienteUDA" onChange="requiredData(this.value)">
														<?php echo $this->bUsuarioUda; ?>
													</select>
												</div>
											</div>
				                		</div>
					                		<div class="span4">
												<div class="control-group divUserUda">
													<label class="control-label">Usuario Ovision:<span class="required"></span></label>
													<div class="controls">
													  <input id="inputUserUda" name="inputUserUda" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['USUARIO_UDA']; ?>">
													</div>
												</div>
					                		</div>
					                		<div class="span4">
												<div class="control-group divUserUda">
													<label class="control-label">Contraseña Ovision:<span class="required"></span></label>
													<div class="controls">
													  <input id="inputPasswordUda" name="inputPasswordUda" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['PASSWORD_UDA']; ?>">
													</div>
												</div>													                			
					                		</div>			                		
				                	</div>	-->

				                	<div class="span12 no-margin-left">
				                		<!--
				                		<div class="span4">
											<div class="control-group">
												<label class="control-label">Cobrar Viajes:<span class="required">*</span></label>
												<div class="controls">												
													<select class="span6 m-wrap"  autocomplete="off" name="inputCobro" >
														<?php echo $this->aCviajes; ?>
													</select>
												</div>
											</div>
				                		</div>-->
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Estatus:<span class="required"></span></label>
													<div class="controls">
														<select class="span6 m-wrap"  autocomplete="off" name="inputEstatus" onChange="requiredData(this.value)">
															<?php echo $this->status; ?>
														</select>
													</div>
												</div>
					                		</div>
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Tipo :<span class="required"></span></label>
													<div class="controls">
														<select class="span12 m-wrap"  autocomplete="off" name="inputTipo">
															<?php echo $this->aTipos; ?>
														</select>
													</div>
												</div>												                			
					                		</div>
					                		<div class="span4">
												<div class="control-group">
												<label class="control-label"># Cliente SAP:<span class="required"></span></label>
													<div class="controls">
													  <input id="inputSap" name="inputSap" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['COD_CLIENTE']; ?>">
													</div>
												</div>													                			
					                		</div>				                		
				                	</div>				                	
				                	<?php if($this->idToUpdate==-1): ?>
					                	<div class="span12 no-margin-left">
											<h4>Datos del Usuario</h4>
										</div>
					                	<div class="span12 no-margin-left">
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Nombre<span class="required">*</span></label>
													<div class="controls">
														<input type="text" name="inputName" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['inputName']; ?>" >
													</div>
												</div>	
					                		</div>
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Apellidos<span class="required">*</span></label>
													<div class="controls">
														<input type="text" name="inputApps" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['inputApps']; ?>" >
													</div>
												</div>					                			
					                		</div>
					                		<div class="span4">
					                			
					                		</div>
					                	</div>	

					                	<div class="span12 no-margin-left">
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Usuario (E-mail)<span class="required">*</span></label>
													<div class="controls">
														<input type="text" name="inputUser" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['inputUser']; ?>" >
													</div>
												</div>				                			
					                		</div>
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Contraseña<span class="required">*</span></label>
													<div class="controls">
														<input type="password" name="inputPassword" autocomplete="off" id="inputPassword" class="span12 m-wrap" value="<?php echo @$this->data['inputPassword']; ?>" >
													</div>
												</div>					                			
					                		</div>
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Confirmar Contraseña<span class="required">*</span></label>
													<div class="controls">
														<input type="password" name="inputPasswordSec" autocomplete="off" autocomplete="off" id="inputPasswordSec"  class="span12 m-wrap" value="<?php echo @$this->data['inputPasswordSec']; ?>" >
													</div>
												</div>					                			
					                		</div>
					                	</div>					                	

					                	<div class="span12 no-margin-left">
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Tel. Fijo:<span class="required">*</span></label>
													<div class="controls">
													  <input name="inputTelFijoUser" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['inputTelFijoUser']; ?>">
													</div>
												</div>
					                		</div>
					                		<div class="span4">
												<div class="control-group">
													<label class="control-label">Tel. Móvil:<span class="required"></span></label>
													<div class="controls">
													  <input name="inputTelMovilUser" type="text" autocomplete="off" class="span12 m-wrap" value="<?php echo @$this->data['inputTelMovilUser']; ?>">
													</div>
												</div>
					                		</div>
					                		<div class="span4">
														                			
					                		</div>			                		
					                	</div>
				                	<?php endif;?>
			               
									<div class="control-group">
									</div>

									<div class="form-actions text-right">
										<a href="javascript:history.back();">
											<button type="button" class="btn">Cancelar</button>
										</a>
										<button type="submit" class="btn btn-primary">Enviar</button>
									</div>
							</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  