<?php $this->headScript()->appendFile('/js/contacts/searchContacts.js') ?>  
<div class="span12">
	<?php if(@$this->aErrors==1):?>
        <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Error</h4>
          <div>El Cliente no esta registrado, verifica el número del Cliente.</div>
        </div>  
	<?php elseif (@$this->aErrors==2):?>
        <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h4>Error</h4>
          <div>El Cliente no cuenta con códigos para activar, verificarlo con el área correspondiente.</div>
        </div>  
	<?php endif;?>

	<?php if($this->bStatusSearch==0):?>
	    <div class="block">
	        <div class="navbar navbar-inner block-header">
	            <div class="muted pull-left">
	            	Activación de Clientes
					<!--<span>Ingrese No. Cliente SAP(<i>ej: CLI00001</i>) </span>-->
				</div>
	        </div>
	        <div class="block-content collapse in">
				<div class="row span12">
					<form method="POST" action="/contacts/main/index" id="FormData" class="form-horizontal ">
						<input type="hidden" name="optReg" value="search" />		
						<fieldset>											
							<div class="row row-margin-left25">
								<div class="span3">Ingrese No. Cliente SAP <i>ej: CLI00001</i></div>
								<div class="span2">
									<div class="control-group">
										<div class="">
											<input type="text" class="span12" id="inputCodeClient" name="inputCodeClient" value="<?php echo ($this->bStatusSearch==0 && @$this->aErrors==2) ? $this->codeClient: '';?>" autocomplete="off"/>
										</div>
									</div>				
								</div>
								<div class="span2">									
									<div class="">
										<button type="submit" class="btn btn-primary">Buscar</button>
									</div>									
								</div>													
							</div>
						</fieldset>
					</form>					
				</div>
			</div>
		</div>
	<?php endif;?>	
	<?php if($this->bStatusSearch!=0):?>
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                	<a href="/contacts/main/index">
						<i class="icon-circle-arrow-left fa-1"></i></a>  Cliente <?php echo ($this->codeClient!=-1) ? $this->codeClient: '';?> </div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">                   
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                            	<th>#</th>
                                <th>Clave Qr</th>
                                <th>Fecha Creación</th>
                                <th>Estatus Código</th>                                
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>     
                        	<?php $counter=1;?>
                            <?php foreach($this->datatTable as $key => $items): ?>  
                            <tr class="odd gradeX">
                            	<td><?php echo $counter; ?></td>
                                <td><?php echo $items['CADENA_QR']; ?></td>
                                <td><?php echo $items['FECHA_CREADO'];?></td>
                                <td><?php echo ($items['FECHA_ACTIVACION']!=NULL) ? $items['N_CLIENTE'].'<br/>'.$items['FECHA_ACTIVACION'] : 'No'; ?></td>
                                <td class="text-center">
                                	<a href="/contacts/main/activation?activationCode=<?php echo $items['ID_QR']; ?>&inputCodeClient=<?php echo $items['COD_CLIENTE']; ?>">
	                                	<?php if($items['FECHA_ACTIVACION']!=NULL): ?>
	                                		<button class="btn btn-info"> <i class="icon-eye-open icon-white"></i></button>
	                                	<?php else:?>
	                                		<button class="btn btn-warning"> <i class="icon-plus icon-white"> </i></button>
	                                	<?php endif;?>
                                    </a>  
                                </td>
                            </tr> 
                            <?php $counter++;?>   
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>		
	<?php endif;?>
</div>