<?php $this->headScript()->appendFile('/js/modules/branches/validatebranches.js') ?>   
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/leasing/branches/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información de mi Lugar</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/leasing/branches/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>	  
		                	<fieldset>
	                				<div class="span12 no-margin-left">
				                		<div class="span12">
											<div class="control-group">
												<label class="control-label">Nombre<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputDescripcion" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['DESCRIPCION']; ?>" >
												</div>
											</div>	
				                		</div>
				                	</div>


	                				<div class="span12 no-margin-left">
				                		<div class="span6">
				                			<div class="control-group">
												<label class="control-label">Calle<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputCalle" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['CALLE']; ?>" >
												</div>
											</div>	
				                		</div>
										<div class="span6">
				                			<div class="control-group">
												<label class="control-label">Colonia<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputColonia" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['COLONIA']; ?>" >
												</div>
											</div>	
				                		</div>				                		
				                	</div>	

	                				<div class="span12 no-margin-left">
				                		<div class="span6">
				                			<div class="control-group">
												<label class="control-label">Municipio<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputMunicipio" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['MUNICIPIO']; ?>" >
												</div>
											</div>	
				                		</div>
										<div class="span6">
				                			<div class="control-group">
												<label class="control-label">Estado<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputEstado" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['ESTADO']; ?>" >
												</div>
											</div>	
				                		</div>				                		
				                	</div>	

	                				<div class="span12 no-margin-left">
				                		<div class="span6">
					                		<div class="control-group">
												<label class="control-label">CP<span class="required">*</span></label>
												<div class="controls">
													<input type="text" name="inputCP" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['CP']; ?>" >
												</div>
											</div>	
				                		</div>
				                		<div class="span6">
											<div class="control-group">
												<label class="control-label">Estatus:<span class="required"></span></label>
												<div class="controls">
													<select class="span6 m-wrap"  autocomplete="off" name="inputEstatus" onChange="requiredData(this.value)">
														<?php echo $this->status; ?>
													</select>
												</div>
											</div>
				                		</div>				                				                		
				                	</div>	
			               
									<div class="control-group">
									</div>

									<div class="form-actions text-right">
										<a href="/leasing/branches/index">
											<button type="button" class="btn">Cancelar</button>
										</a>
										<button type="submit" class="btn btn-primary">Guardar</button>
									</div>
							</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  