<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/vendors/graphs/js/jquery.circliful.js'); ?>
<?php $this->headScript()->appendFile('/js/dataTables.tableTools.js'); ?>
<?php $this->headLink()->appendStylesheet('/css/dataTables.tableTools.css');?>
<?php $this->headScript()->appendFile('/js/jQuery.print.js'); ?>
<?php $this->headScript()->appendFile('/js/atn/rastreotels.js'); ?>
<?php $control=0?>
<!--<div id="divDataPersonal" class="hide"><?php foreach($this->aTecnicos as $key => $items):?><?php echo ($control==0) ? '': '?';?><?php echo $items['ID']."|".$items['NAME']."|".$items['ID_SUCURSAL'];?><?php $control++;?><?php endforeach;?>
</div>-->
<div class="row panel-data formcustom">
    <div class="span12">    
        <div class="block no-margin-l no-margin-t">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Teléfonos <small>Ubicación</small></div>
            </div>
            <div class="block-content-min collapse in">
			    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
			        <li class="active"><a href="#tabla" data-toggle="tab">Tabular</a></li>
					<li><a href="#mapa" data-toggle="tab" onClick="reDrawMap();">Mapa</a></li>			    	
					<div class="pull-right">
						<form method="POST" action="/atn/rastreo/index" id="FormData" class="form-horizontal formcustom">
                            <input type="hidden" name="optReg" value="search" />
                            <input type="hidden" name="inputStatus" id="inputStatus" value="<?php echo $this->iStatus; ?>" />
	                		<div class="span10">
	                			<div class="span3">
	                				<label>Sucursal</label>
	                			</div>
	                			<div class="span9">
									<select class="chzn-select" id="inputSucursal" name="inputSucursal" onChange="submitForm();">
										<option value="-1">Todos</option>
										<?php echo $this->cInstalaciones;?>
									</select>
	                			</div>
	                		</div>						
	                	</form>
					</div>
			    </ul>			    

			    <div id="my-tab-content" class="tab-content bg-white">
			        <div class="tab-pane active" id="tabla">  
			        	<div class="row row-margin-left25 ">			        			
		                      <div class="span2 hide-sidebar <?php echo ($this->iStatus==-1) ? 'status-selected':'';?>" onClick="setStatus(-1)">
		                            <div class="graphCircle" 
		                                data-dimension="150" 
		                                data-text="<?php echo $this->aResume['TOTAL'];?>" 
		                                data-info="Total Teléfonos" 
		                                data-width="30" 
		                                data-fontsize="38" 
		                                data-percent="100" 
		                                data-fgcolor="#2D66F5" 
		                                data-bgcolor="#E2E2E2" 
		                                data-fill="#F3F3F3"></div>
		                        </div> 
		                        
		                        <?php foreach($this->aResume as $key => $items):?>
		                        	<?php if(isset($items['COLOR'])):?>
										<?php $porcentaje = (round($items['TOTAL'] / $this->aResume['TOTAL'] * 100, 0)); ?>
				                        <div class="span2 hide-sidebar <?php echo ($this->iStatus==$items['N_ESTATUS']) ? 'status-selected':'';?>" onClick="setStatus('<?php echo $items['N_ESTATUS']; ?>')">
				                            <div class="graphCircle" 
				                                data-dimension="150" 
				                                data-text="<?php echo $items['TOTAL'];?>" 
				                                data-info="<?php echo $items['DESC'];?>" 
				                                data-width="30" 
				                                data-fontsize="38" 
				                                data-percent="<?php echo $porcentaje;?>" 
				                                data-fgcolor="<?php echo $items['COLOR'];?>" 
				                                data-bgcolor="#E2E2E2" 
				                                data-fill="#F3F3F3"></div>
				                        </div>
		                        	<?php endif;?>		                        	
		                        <?php endforeach;?>           
		                </div>
		                <div class="row row-margin-left25 ">

		                    <div class="button-excel-rel">
		                        <?php if(count($this->aPocisiones)>0): ?>
		                            <div class="btn-group">
		                             <a href="javascript:getReportAll()"><button class="btn btn-success"> Exportar <i class="icon-file icon-white"></i></button></a>                                    
		                            </div>
		                             <!--<div class="btn-group">
		                                <button onClick="printPage()" class="btn btn-primary"> Imprimir <i class="icon-print icon-white"></i></button>
		                            </div>-->
		                        <?php endif;?>
		                    </div>                        
		                    <table cellspacing="0" width="100%" class="table table-striped table-bordered display"  id="dataTable">
		                        <thead>             
		                            <tr>
		                            	<th>Estatus</th>
		                            	<th>Sucursal</th>
		                            	<th>Tecnico</th>
		                            	<th>Identificador</th>
		                            	<th>Últ. Evento</th>
		                            	<th>Últ. Reporte</th>		                            	
		                            	<th>Ubicacion</th>
		                            	<th></th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <?php $result = '';$print=false?>
		                            <?php foreach($this->aPocisiones as $key => $items): ?>
                                		<?php $print = (isset($this->iStatus) && $this->iStatus != -1) ? (($this->iStatus==$items['N_ESTATUS']) ? true : false) : true; ?>
                                		<?php if($print):?>		                            
		                                    <tr>
		                                    	<td>
		                                    		<img src="/images/<?php echo ($items['N_ESTATUS']=='OK') ? 'carMarker' : 'carOff'; ?>.png">
		                                    	</td>
		                                    	<td><?php echo $items['N_SUCURSAL'];?></td>
		                                    	<td><?php echo $items['N_TECNICO'];?></td>  
		                                    	<td><?php echo $items['IDENTIFICADOR'];?></td>  
		                                    	<td><?php echo $items['N_EVENTO'];?></td>  
		                                    	<td><?php echo $items['FECHA_GPS'];?></td>  
		                                    	<td><?php echo $items['UBICACION'];?></td>
		                                        <td class="text-center" style="width:50px;"> 
													<div class="btn-group">
														<button class="btn btn-primary" onClick="getReport(<?php echo $items['ID_TELEFONO']; ?>)" data-toggle="tooltip" data-placement="bottom" title="Historico del Técnico"><i class="icon-globe icon-white"></i></button>
													</div>
		                                        </td>
		                                    </tr>  
                                		<?php endif;?>
		                            <?php endforeach;?>
		                        </tbody>
		                    </table>                                    
		                </div>
			        </div>			    	
			        <div class="tab-pane " id="mapa">  
						<div class="span12">
							<div class="span3 row panel-data formcustom">
								<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable2">
	                                <thead>
	                                    <tr>	        
	                                    	<th>Estatus</th>                                
	                                        <th>Técnico</th>
	                                        <th></th>
	                                    </tr>
	                                </thead>
	                                <tbody>                                
			                            <?php $result = '';$print=false?>
			                            <?php foreach($this->aPocisiones as $key => $items): ?>
	                                		<?php $print = (isset($this->iStatus) && $this->iStatus != -1) ? (($this->iStatus==$items['N_ESTATUS']) ? true : false) : true; ?>
	                                		<?php if($print):?>		                            
			                                    <tr>
			                                    	<td>
			                                    		<img src="/images/<?php echo ($items['N_ESTATUS']=='OK') ? 'carMarker' : 'carOff'; ?>.png"  data-toggle="tooltip" data-placement="right" title="Últ. Reporte: <?php echo $items['FECHA_GPS'];?>">
			                                    	</td>
			                                    	<td><?php echo $items['N_TECNICO'];?></td>  
			                                    	<td>
			                                    		<button class="btn btn-success btnCenter" onClick="centerTel(<?php echo $items['ID_TELEFONO']; ?>)"  data-toggle="tooltip" data-placement="bottom" title="Centrar el Teléfono"><i class="icon-map-marker icon-white"></i></button>
			                                    	</td>
			                                    </tr>  
												<?php $result .= ($result!="") ? "!" : "";?>
												<?php $resultInd =  $items['ID_TELEFONO']."|".
																 $items['FECHA_TELEFONO']."|".
																 $items['TIPO_GPS']."|".
																 $items['N_EVENTO']."|".
																 $items['LATITUD']."|".
																 $items['LONGITUD']."|".
																 round($items['VELOCIDAD'],2)."|".
																 round($items['NIVEL_BATERIA'],2)."|".
																 $items['UBICACION']."|".
																 $items['N_ESTATUS'];?>
												<?php $result .= $resultInd;?>
												<div class="hide" id="divTel<?php echo $items['ID_TELEFONO']; ?>"><?php echo $resultInd;?></div>				 			                                    
	                                		<?php endif;?>
			                            <?php endforeach;?>	                                    
	                                </tbody>
	                            </table>
	                            <div id="positions" class="hide"><?php echo $result; ?></div> 								
							</div>
		                	<div class="span9 block">
			                    <div id="Map" style="width:100%;height:500px;">

			                    </div>  
			                    <div class="">                      
			                    </div>                                         
			                </div>
			            </div>
			        </div>
			    </div>
            </div>
        </div>
    </div>
</div>    

<div class="modal fade hide modal-lg" id="myModalMapa" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
    	<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4 class="modal-title" ></h4>
      	</div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameModalMapa" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>	