<?php $this->headScript()->appendFile('/js/marketing/listForms.js') ?>   
<div class="block-content collapse in" id="divLoading" style="display:none;">
    <img id="loaderForms" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/> 
</div>
<div class="block no-margin" id="divTable">
    <?php if($this->resultOp=='okRegister'): ?>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            Datos se almacenaron correctamente.
        </div>                                                          
    <?php endif; ?>
    <form method="POST" action="/marketing/sapclientes/clientforms?strInput=<?php echo $this->data['COD_CLIENTE'];?>" id="FormData" class="form-horizontal ">
        <input type="hidden" id="optReg"   name="optReg" value="updateListForms" />
        <input type="hidden" id="strInput" name="strInput" value="<?php echo $this->data['COD_CLIENTE'];?>" />    

        <div class="block-content collapse in" style="overflow-y: auto; height:440px; ">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                <thead>
                    <tr>
                        <th><input type="checkbox" onChange="optionAll(this.checked)"> Todos</th>
                        <th>Titulo</th>
                        <th>Descripción</th>
                        <th>Id Ovision</th>
                        <th>Icono</th>
                    </tr>
                </thead>
                <tbody>                                
                    <?php foreach($this->dataTable as $key => $items): ?>  
                    <tr class="odd gradeX">
                        <td>
                            <input class="chkOn" name="formsValues[]"  type="checkbox" value="<?php echo $items['ID'];?>" <?php echo ($items['ASIGNADO']==1) ? 'checked':'';?> />
                        </td>
                        <td><?php echo $items['TITULO']; ?></td>
                        <td><?php echo $items['DESCRIPCION']; ?></td>
                        <td><?php echo $items['ID_OVISION']; ?></td>
                        <td><img style="width:30px;" src="/images/icons/<?php echo $items['N_IMAGEN']; ?>"/></td>
                    </tr>    
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
        <div class="form-group m-top-1">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="pull-right">
                    <button type="submit" class="btn btn-info">Guardar Cambios</button>
                </div>
            </div>
        </div> 
    </form>
</div>