<div class="row bg-white panel-data row-min-h">
    <div class="col-md-12 text-center">
        <div class="alert alert-error">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <h4>¡Atención!</h4>
            El código solicitado aun no se encuentra disponible, espere 30 segs. e inténtelo de nuevo. <br/>
            <a href="javascript:window.history.back();"> 
                <button type="button" class="btn" ><i class="icon-circle-arrow-left fa-1"></i>Regresar</button>
            </a>
        </div>        
    </div>
</div>

