<?php $this->headScript()->appendFile('/js/marketing/validateCodes.js') ?>  
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/marketing/sapclientes/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMainModule()">
						<i class="icon-circle-arrow-left fa-1"></i></a> Cliente: <?php echo '('.$this->data['COD_CLIENTE'].') '.$this->data['RAZON_SOCIAL']; ?></div>
            </div>
            <div class="block-content collapse in">
				<div class="row span12">
	                <?php if(@$this->okCodes): ?>
	                    <div class="alert alert-success">
	                        <button type="button" class="close" data-dismiss="alert">×</button>
	                        Los códigos se han generado de manera correcta.
	                    </div>  		              
	                <?php endif; ?>
							
					<form method="POST" action="/marketing/sapclientes/getinfo?catId=<?php echo $this->catId; ?>" id="FormData" class="form-horizontal ">
						<input type="hidden" name="optReg" value="new" />
						<input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
					
						<fieldset>											
							<div class="row row-margin-left25">
								<div class="span2"># Códigos a generar </div>
								<div class="span2">
									<div class="control-group">
										<div class="">
											<input type="text" class="span12" id="txtTotalCodes" name="txtTotalCodes" value="1"/>
										</div>
									</div>				
								</div>
								<div class="span2">									
									<div class="">
										<button type="submit" class="btn btn-primary">Generar</button>
									</div>									
								</div>													
							</div>
						</fieldset>
					</form>							
				</div>
				<div class="row span11">
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th>#</th>                                
                                <th>Clave</th>
                                <th>Fecha Creación</th>
                                <th>Activado</th>
                                <th class="text-center">
                                	<?php if(count($this->dataTable)>0 ):?>
										<a href="/marketing/sapclientes/exportallcard?catId=<?php echo $this->catId; ?>">
		                                    <button class="btn btn-info"> <i class="icon-file icon-white"></i>
		                                    </button>
		                                </a>                                   	
                                	<?php endif;?>	
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                        	<?php $countCodes = 1;?>
                            <?php foreach(@$this->dataTable as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $countCodes; $countCodes++;?></td>
                                <td><?php echo $items['CADENA_QR']; ?></td>
                                <td><?php echo $items['FECHA_CREADO']; ?></td>
                                <td><?php echo ($items['FECHA_ACTIVACION']!=NULL) ? $items['N_CLIENTE'].'<br/>'.$items['FECHA_ACTIVACION'] : 'No'; ?></td>
                                <td class="text-center">
	                                <a href="/marketing/sapclientes/exportcard?catId=<?php echo $items['ID_QR']; ?>">
	                                    <button class="btn btn-info"> <i class="icon-file icon-white"></i>
	                                    </button>
	                                </a>                                	

                                    <!--<?php if($this->dataUser['ELIMINAR']==1): ?>
										<form method="POST" action="/main/equipment/getinfo" id="FormData" class="formcustom">
											<input type="hidden" name="optReg" value="deleteEvent" />
											<input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
											<input type="hidden" id="idRelation" name="idRelation" value="<?php echo $items['ID_EVENTO_EQUIPO']; ?>" />
                                        	<button type="submit" class="btn btn-danger"> <i class="icon-trash icon-white"></i></button>
                                        </form>
                                    <?php endif;?>-->
                                </td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>							
				</div>		
			</div>
		</div>
	</div>	
</div> 

<div class="modal fade hide" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Activos Sin Asignar</h4>
      </div>
      <div class="modal-form i-body">             
		<iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>	 