<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>   
<?php $this->headScript()->appendFile('/js/marketing/listClientesSap.js') ?>  
<div class="row panel-data">

    <input id="hRefLinkEdit" type="hidden" value="/main/sapclintes/getinfo?idRow=" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Clientes SAP</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <?php if($this->dataUser['INSERTAR']==1): ?>
                        <div class="table-toolbar">
                          <!--
                          <div class="btn-group">
                             <a href="/main/sapclintes/getinfo?catId=-1"><button class="btn btn-success"> Agregar <i class="icon-plus icon-white"></i></button></a>
                          </div>-->
                        </div>  
                    <?php endif;?>  
                    <div class="button-excel-rel">
                        <?php if(count($this->datatTable)>0): ?>
                            <div class="btn-group">
                             <a  target="_blank" href="/marketing/sapclientes/exportall"><button class="btn btn-success"> Exportar <i class="icon-file icon-white"></i></button></a>                                    
                            </div>
                             <!--<div class="btn-group">
                                <button onClick="printPage()" class="btn btn-primary"> Imprimir <i class="icon-print icon-white"></i></button>
                            </div>-->
                        <?php endif;?>
                    </div>                                              
                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                        <thead>
                            <tr>
                                <th># SAP</th>
                                <th>Nombre</th>
                                <th>Razón Social</th>                                
                                <th>QR`s Activados</th>
                                <th>QR`s Sin Activar</th>
                                <th>Total QR`s</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php foreach($this->datatTable as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $items['COD_CLIENTE']; ?></td>
                                <td><?php echo ($items['NAME']!='NULL') ? $items['NAME']: '--';?></td>
                                <td><?php echo $items['RAZON_SOCIAL']; ?></td>
                                <td><?php echo $items['ACTIVATE_QR']; ?></td>
                                <td><?php echo $items['INACTIVATE_QR']; ?></td>
                                <td><?php echo $items['TOTAL_QR']; ?></td>

                                <td class="text-center" style="width:160px;"> 
                                        <div class="span3">
                                            <a href="/marketing/sapclientes/getinfo?catId=<?php echo $items['COD_CLIENTE']; ?>">
                                                <button type="button" class="btn btn-primary" data-toggle="tooltip" data-placement="left" title="Generar QR`s"><i class="icon-qrcode icon-white"></i></button>
                                            </a>
                                        </div>
                                        <div class="span3">
                                            <a href="javascript:migrateUnits('<?php echo $items['COD_CLIENTE']; ?>')">
                                                <button type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="top" title="Sincronizar Unidades con Ovision"><i class="icon-plane icon-white"></i></button>
                                            </a>
                                        </div>
                                        <div class="span3">
                                            <a href="javascript:assignForms('<?php echo $items['COD_CLIENTE']; ?>')">
                                                <button type="button" class="btn btn-info" data-toggle="tooltip" data-placement="bottom" title="Formularios"><i class="icon-list-alt icon-white"></i></button>
                                            </a>  
                                        </div>
                                </td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>   

<div id="modalConfirmDelete" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Atención!</h3>
    </div>
    <div class="modal-body">
        <p>¿Realmente desea eliminar este registro?</p>
    </div>
    <div class="modal-footer">
        <input type="hidden" id="inputDelete" value="-1"/>
        <a class="btn btn-primary" href="javascript:deleteRow();">Eliminar</a>
        <a data-dismiss="modal" class="btn" href="#">Cancelar</a>
    </div>
</div>  


<div class="modal fade hide modal-lg" id="divModalUnits" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" ></h4>
        </div>
      <div class="modal-form i-body"> 
        <img id="loader" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>            
        <iframe class="hmodal500" id="iFrameUnits" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>

<div class="modal fade hide modal-lg" id="divModalForms" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" ></h4>
        </div>
      <div class="modal-form i-body"> 
        <img id="loaderForms" class="offset4" src="/images/assets/loading.gif" alt="loading gif"/>            
        <iframe class="hmodal500" id="iFrameForms" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>