 <?php $this->headScript()->appendFile('/js/callcenter/callservice.js') ?>   
   <div class="row panel-data">
		<div class="span12">			
        	<div class="block row-min-h">
    		    <div class="col-md-12 text-center">
			        <h3>Los datos se han guardado correctamente.</h3>
			        <button type="button" onclick="location.href='/callcenter/callservice/index'" class="btn btn-large btn-primary">Nuevo Servicio</button>    		    	
    		    </div>
        	</div>
    	</div>
	</div>    