 <?php $this->headScript()->appendFile('/js/callcenter/newservice.js') ?>   
   <div class="row panel-data">
		<div class="span12">			
        	<div class="block row-min-h">
				<div class="navbar">
					<div class="navbar-inner">
				        <ul class="breadcrumb">				            
				            <li class="active">
				                <a href="javascript:void()">Datos del Cliente</a> <span class="divider">/</span>	
				            </li>				            
				        </ul>
					</div>
				</div>
				<form method="POST" action="/callcenter/callservice/index" id="FormData" class="form-horizontal ">
                	<input type="hidden" id="inputOpr"    name="optReg" value="new" />
					<input type="hidden" id="typeSearch"  name="typeSearch"  value="" />
					<input type="hidden" id="inputSearch" name="inputSearch" value="" />
					<fieldset>
						<div class="row span12 row-margin-left25">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Tipo Cliente<span class="required">*</span></label>
									<div class="controls">
										<select class="span10 m-wrap" id="inputTipo" name="inputTipo" onChange="changeTypePerson(this.value)" onClick="changeTypePerson(this.value)">
											<option value="">Seleccionar una opción</option>													
											<?php echo $this->tipoCliente;?>
										</select>										
									</div>
								</div>				
							</div>
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Tipo Servicio<span class="required">*</span></label>
									<div class="controls">
										<select class="span10 m-wrap" id="inputTipService" name="inputTipService">
											<option value="">Seleccionar una opción</option>													
											<?php echo $this->tipoService;?>
										</select>
									</div>
								</div>							
							</div>						
						</div>
						<div id="divMoral" style="display:<?php echo (@$this->data['inputTipo']=='M' ) ? 'block': 'none';?>;">
							<div class="row span12 row-margin-left25">
								<div class="span5">
									<div class="control-group">
										<label class="control-label-lg">RFC<span class="required">*</span></label>
										<div class="controls">
											<input id="inputRFC" name="inputRFC" type="text" class="form-control upper" value="<?php echo @$this->data['inputRFC']; ?>" >
										</div>
									</div>				
								</div>
								<div class="span5">
									<div class="control-group">
										<label class="control-label-lg">Razón Social<span class="required">*</span></label>
										<div class="controls">
											<input id="inputRazon" name="inputRazon" type="text" class="form-control upper" value="<?php echo @$this->data['inputRazon']; ?>" >
										</div>
									</div>							
								</div>						
							</div>

							<div class="row span12">
								<div class="span12">
									<div class="control-group">
										<label class="control-label-lg">Clave Cliente</label>
										<div class="controls">
											<input type="text" id="inputClave" name="inputClave" class="m-wrap upper" value="<?php echo (@$this->data['inputClave']); ?>"  >
										</div>
									</div>
								</div>						
							</div>

						</div>

						<div class="row span12 ">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Nombre(s)<span class="required">*</span></label>
									<div class="controls">
				                        <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNombre']; ?>" >
									</div>
								</div>				
							</div>
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Apellidos<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputApps" name="inputApps" class="m-wrap upper" value="<?php echo (@$this->data['inputApps']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>
						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Fecha de Nacimiento</label>
									<div class="controls">
				                          <input id="inputNac" readonly name="inputNac"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNac']; ?>" data-date-format="YYYY-MM-DD">
									</div>
								</div>				
							</div>
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Género<span class="required">*</span></label>
									<div class="controls">
										<select class="span10 m-wrap" id="inputGenero" name="inputGenero">
											<option value="">Seleccionar una opción</option>													
											<?php echo $this->genero;?>
										</select>
									</div>
								</div>							
							</div>						
						</div>		
						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Teléfono Fijo<span class="required">*</span></label>
									<div class="controls">
				                          <input id="inputTel" name="inputTel" data-required="1"  type="tel" class="form-control upper" value="<?php echo @$this->data['inputTel']; ?>" >
									</div>
								</div>				
							</div>
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Teléfono móvil<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputCel" name="inputCel" class="m-wrap upper" value="<?php echo (@$this->data['inputCel']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>	
						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Correo electrónico<span class="required">*</span></label>
									<div class="controls">
				                          <input id="inputEmail" name="inputEmail" data-required="1"  type="email" class="form-control" value="<?php echo @$this->data['inputEmail']; ?>" >
									</div>
								</div>							
							</div>	
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Confirmar correo<span class="required">*</span></label>
									<div class="controls">
				                          <input id="inputEmailConf" name="inputEmailConf" data-required="1"  type="email" class="form-control" value="<?php echo @$this->data['inputEmailConf']; ?>" >
									</div>
								</div>							
							</div>													
						</div>										

						<div class="row span12">
							<div class="span12">
								<div class="control-group">
									<label class="control-label-lg">Calle.<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputStreet" name="inputStreet" class="span9 m-wrap upper" value="<?php echo (@$this->data['inputStreet']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>	
						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">No. Ext<span class="required">*</span></label>
									<div class="controls">
				                          <input id="inputNoExt" name="inputNoExt" data-required="1"  type="text" class="form-control upper" value="<?php echo @$this->data['inputNoExt']; ?>" >
									</div>
								</div>				
							</div>
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">No. Int<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputNoInt" name="inputNoInt" class="m-wrap upper" value="<?php echo (@$this->data['inputNoInt']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>						


						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">C.P<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputCP" name="inputCP" class="m-wrap upper" value="<?php echo (@$this->data['inputCP']); ?>"  >
									</div>
								</div>							
							</div>						
							<div class="span5">
								<div class="control-group">
									<button type="button" class="btn btn-default bg-btn-send" onClick="searchCp(0)">Buscar por CP</button>
								</div>				
							</div>							
						</div>


						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Estado<span class="required">*</span></label>
									<div class="controls">
										<select class="span10 m-wrap upper" id="inputEstado" name="inputEstado" onChange="getoptionsCbo('Municipio','mun',this.value,false,'colonia');">
											<option value="">Seleccionar una opción</option>
											<?php echo $this->estados; ?>
					                    </select>
									</div>
								</div>							
							</div>											
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Municipio<span class="required">*</span></label>
									<div class="controls">
										<div id="divMunicipio">
											<select class="span10 m-wrap upper" id="inputMunicipio" name="inputMunicipio" onChange="getoptionsCbo('colonia','colonia',this.value,false,'');">
												<option value="">Seleccionar una opción</option>
												<?php echo $this->municipios; ?>
											</select>
										</div>												
									</div>
								</div>				
							</div>					
						</div>
					
						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Colonia<span class="required">*</span></label>
									<div class="controls">
										<div id="divcolonia">
											<select class="span10 m-wrap upper" id="inputcolonia" name="inputcolonia" <?php echo (isset($this->data['inputcolonia'])) ? 'onChange(getCPdir(this.value,"colonia"))': '';?>>
												<option value="">Seleccionar una opción</option>
												<?php echo $this->colonias;?>
											</select>
										</div>		
									</div>
								</div>				
							</div>
							<!--<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">C.P<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputCP" name="inputCP" class="m-wrap upper" value="<?php echo (@$this->data['inputCP']); ?>"  >
									</div>
								</div>							
							</div>	-->					
						</div>
						<div class="row span12">
							<div class="span12">
								<div class="control-group">
									<label class="control-label-lg">Referencias<span class="required">*</span></label>
									<div class="controls">
										<input type="text" id="inputRefs" name="inputRefs" class="span9 m-wrap upper" value="<?php echo (@$this->data['inputRefs']); ?>"  >
									</div>
								</div>							
							</div>						
						</div>	

						<div class="row span12">
							<div class="span5">
								<div class="control-group">
									<label class="control-label-lg">Instalacion en Domicilio del Cliente<span class="required">*</span></label>
									<div class="controls">
										<select class="span10 m-wrap" id="inputDom" name="inputDom" onChange="differentDom(this.value)">
											<?php echo $this->mismoDomicilio; ?>
					                    </select>	
									</div>
								</div>							
							</div>											
							<div class="span5">
								<div id="cboOptsDom" style="display:<?php echo (@$this->data['inputDom']==0 && isset($this->data['inputDom'])) ? 'display':'none';?>;">
									<div class="control-group">
										<label class="control-label-lg">Domicilio de la instalación<span class="required">*</span></label>
										<div class="controls">
											<select class="span10 m-wrap" id="inputDirDom" name="inputDirDom" onChange="showFormDirection(this.value);">
												<option value="0">Seleccionar una opción</option>
												<?php echo $this->dirDomicilio; ?>
						                    </select>
										</div>
									</div>				
								</div>
							</div>					
						</div>

						<div id="divDifDom" style="display:<?php echo (@$this->data['inputDirDom']==2 && isset($this->data['inputDirDom']) && $this->inputDom==1) ? 'display':'none';?>;">

							<div class="row span12">
									<div class="span12">
										<div class="control-group">
											<label class="control-label-lg">Calle.<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputStreetO" name="inputStreetO" class="span9 m-wrap upper" value="<?php echo (@$this->data['inputStreetO']); ?>"  >
											</div>
										</div>							
									</div>						
								</div>	
								<div class="span12">
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">No. Ext<span class="required">*</span></label>
											<div class="controls">
						                          <input id="inputNoExtO" name="inputNoExtO" type="text" class="form-control upper" value="<?php echo @$this->data['inputNoExtO']; ?>" >
											</div>
										</div>				
									</div>
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">No. Int<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputNoIntO" name="inputNoIntO" class="m-wrap upper" value="<?php echo (@$this->data['inputNoIntO']); ?>"  >
											</div>
										</div>							
									</div>						
								</div>						

								<div class="row span12">
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">Estado<span class="required">*</span></label>
											<div class="controls">
												<select class="span10 m-wrap upper" id="inputEstadoO" name="inputEstadoO" onChange="getoptionsCbo('MunicipioO','mun',this.value,false,'coloniaO');">
													<option value="">Seleccionar una opción</option>
													<?php echo $this->estados; ?>
							                    </select>
											</div>
										</div>							
									</div>											
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">Municipio<span class="required">*</span></label>
											<div class="controls">
												<div id="divMunicipioO">
													<select class="span10 m-wrap upper" id="inputMunicipioO" name="inputMunicipioO" onChange="getoptionsCbo('coloniaO','colonia',this.value,false,'');">
														<option value="">Seleccionar una opción</option>
														<?php echo $this->municipios; ?>
													</select>
												</div>												
											</div>
										</div>				
									</div>					
								</div>
							
								<div class="row span12">
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">Colonia<span class="required">*</span></label>
											<div class="controls">
												<div id="divcoloniaO">
													<select class="span10 m-wrap upper" id="inputcoloniaO" name="inputcoloniaO" <?php echo (isset($this->data['inputcoloniaO'])) ? 'onChange="getCPdir(this.value,\'coloniaO\')"': '';?>>
														<option value="">Seleccionar una opción</option>
														<?php echo $this->colonias;?>
													</select>
												</div>		
											</div>
										</div>				
									</div>
									<div class="span5">
										<div class="control-group">
											<label class="control-label-lg">C.P<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputCPO" name="inputCPO" class="m-wrap upper" value="<?php echo (@$this->data['inputCPO']); ?>"  >
											</div>
										</div>							
									</div>						
								</div>
								<div class="row span12">
									<div class="span12">
										<div class="control-group">
											<label class="control-label-lg">Referencias<span class="required">*</span></label>
											<div class="controls">
												<input type="text" id="inputRefsO" name="inputRefsO" class="span9 m-wrap upper" value="<?php echo (@$this->data['inputRefsO']); ?>"  >
											</div>
										</div>							
									</div>						
								</div>	
						</div>
						<div class="span11">
					    	<div class="col-xs-4 col-md-5">
								<div class="pull-right">
									<button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>			
									<button type="submit" class="btn btn-default bg-btn-send">Continuar</button>
								</div>    
					    	</div>						
						</div>
					</fieldset>	                	
                </form>	
        	</div>
    	</div>
	</div>   	 