 <?php $this->headScript()->appendFile('/js/callcenter/newservice.js') ?>   
 <?php $options = Array('Ninguno','Id Viaje','Sucursal','Transportista'); ?>
 <!-- 
Datos personales todos requeridos

Vehiculo
Placas
serie
año
color

-->
   <div class="row panel-data">
		<div class="span12">
        	<div class="block">
				<form method="POST" action="/main/map/infotravel" id="FormData" class="form-horizontal ">
                	<input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                	<input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
                        <div id="rootwizard">
                            <div class="navbar">
                              <div class="navbar-inner">
                                <div class="container">
                            <ul>
                                <li><a href="#tab1" data-toggle="tab">Registro del Cliente</a></li>
                                <li><a href="#tab2" data-toggle="tab">Ubicación de la Instalación</a></li>
                                <li><a href="#tab3" data-toggle="tab">Datos del Vehiculo</a></li>
                                <li><a href="#tab4" data-toggle="tab">Agendar Cita</a></li>
                            </ul>
                             </div>
                              </div>
                            </div>
                            <div class="tab-content">
                                <div class="tab-pane" id="tab1">
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Nombre(s)<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Apellidos<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Fecha de Nacimiento<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Género<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>		
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Teléfono Fijo<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Teléfono móvil<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Correo electrónico<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Estado<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Municipio<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">C.P<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>										

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>																																																						
                                </div>
                                <div class="tab-pane" id="tab2">
                                	<div id="Map">Aqui Va el Mapa</div>
                                	<div id="dirInstalacion">
                                		<h1>Centro de Instalacion</h1>

                                	</div>
                                </div>
                                <div class="tab-pane" id="tab3">
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Calle y No.<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	

									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Colonia<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>					
									</div>																																														
                                </div>
                                <div class="tab-pane" id="tab4">
									<div class="">
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Dia de Instalación<span class="required">*</span></label>
												<div class="controls">
							                          <input id="inputNombre" name="inputNombre" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputNombre']; ?>" >
												</div>
											</div>				
										</div>
										<div class="span5">
											<div class="control-group">
												<label class="control-label-lg">Horario<span class="required">*</span></label>
												<div class="controls">
													<input type="text" id="inputApps" name="inputApps" class="m-wrap" value="<?php echo (@$this->data['inputApps']); ?>"  >
												</div>
											</div>							
										</div>						
									</div>	
                                </div>
                                <ul class="pager wizard">
                                    <!--<li class="previous first" style="display:none;"><a href="javascript:void(0);">First</a></li>-->
                                    <li class="previous"><a style="display:none;" href="javascript:void(0);">Anterior</a></li>
                                    <!--<li class="next last" style="display:none;"><a href="javascript:void(0);">Last</a></li>-->
                                    <li class="next"><a href="javascript:void(0);">Siguiente</a></li>
                                    <li class="next finish" style="display:none;"><a href="javascript:void(0);">Guardar</a></li>
                                </ul>
                            </div>  
                        </div>
                    </form>
        	</div>
    	</div>
	</div>    