<?php $this->headScript()->appendFile('/js/companies/validateCompanies.js') ?>   
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/leasing/clients/index" />
	<div class="span12">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
					<a href="javascript:backToMain()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
                	Información del Cliente</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
					<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
						<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
						  <button type="button" class="close" data-dismiss="alert">×</button>
						  <h4>Error</h4>
						  <div>Usted no tiene permiso para ver esta información</div>
						</div>						
					<?php else:?>	
					<!-- BEGIN FORM-->
					<?php if($disabled!='disabled'):?>
					<form method="POST" action="/leasing/clients/getinfo" id="FormData" class="form-horizontal ">
					<?php endif;?>	
		                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		                <?php if(count(@$this->errors)>0):?>
		                    <?php if(@$this->errors['eEmpresa']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>La empresa ya se encuentra registrada, pongase en contacto con su administrador para crear su cuenta.</div>
								</div>		
		                    <?php elseif(@$this->errors['eUsuario']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>El usuario ya se encuentra registrado, favor de verificarlo.</div>
								</div>		                    							                    
		                    <?php elseif(@$this->errors['status']==1):?>
								<div class="alert alert-error" style="display:block;">
									<button type="button" class="close" data-dismiss="alert">×</button>
									<b>¡Atención Error!</b>
									<div>Ocurrio un error en el registro, favor de intentarlo mas tarde.</div>
								</div>
		                    <?php endif;?>    
		                <?php endif; ?>    
		                	<fieldset>
                				<div class="span12 no-margin-left">
			                		<div class="span12">
										<div class="control-group">
											<label class="control-label">Nombre<span class="required">*</span></label>
											<div class="controls">
												<input type="text" name="inputDescripcion" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['NOMBRE']; ?>" >
											</div>
										</div>	
			                		</div>
			                	</div>

                				<div class="span12 no-margin-left">
			                		<div class="span12">
			                			<div class="control-group">
											<label class="control-label">Razón Social<span class="required">*</span></label>
											<div class="controls">
												<input type="text" name="inputRazonSocial" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['RAZON_SOCIAL']; ?>" >
											</div>
										</div>	
			                		</div>
			                	</div>	
			                	
                				<div class="span12 no-margin-left">
			                		<div class="span12">
			                			<div class="control-group">
											<label class="control-label">RFC<span class="required">*</span></label>
											<div class="controls">
											  <input name="inputRFC" type="text" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['RFC']; ?>" >
											</div>
										</div>	
			                		</div>
			                	</div>	

			                	<div class="span12 no-margin-left">
			                		<div class="span4">
										<div class="control-group">
											<label class="control-label">Estatus:<span class="required"></span></label>
											<div class="controls">
												<select class="span6 m-wrap"  autocomplete="off" name="inputEstatus" onChange="requiredData(this.value)">
													<?php echo $this->status; ?>
												</select>
											</div>
										</div>
			                		</div>
			                	</div>
			                	
								<div class="control-group">
								</div>

								<div class="form-actions text-right">
									<a href="javascript:history.back();">
										<button type="button" class="btn">Cancelar</button>
									</a>
									<button type="submit" class="btn btn-primary">Guardar</button>
								</div>
							</fieldset>
					<?php if($disabled!='disabled'):?>
					</form>
					<?php endif;?>
					<!-- END FORM-->																
					<?php endif;?>
				</div>
		    </div>
		</div>
	</div>
</div>  