<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?> 
   <div class="row panel-data">
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Búsqueda</div>
                </div>
                <div class="block-content collapse in">
                    <form method="POST" action="/callcenter/rastreo/index" id="FormData" class="form-horizontal ">
                        <input type="hidden" name="option" value="getReport" />
                        <fieldset>
                            <div class="row">
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label">Buscar</label>
                                        <div class="controls">
                                            <input type="text" class="span12" id="inputSearch" name="inputSearch" value="<?php echo (@$this->data['inputSearch']); ?>">
                                        </div>
                                    </div>                          
                                </div> 
                                <div class="span4">
                                    <div class="pull-right">            
                                        <button type="submit" class="btn btn-default bg-btn-send">Buscar</button>
                                    </div>   
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>            
    </div>

    <div class="row panel-data">
        <div class="span12">
            <!-- block -->
            <div class="block">
                <div class="navbar navbar-inner block-header">
                    <div class="muted pull-left">Resultados de la Búsqueda</div>
                </div>
                <div class="block-content collapse in row-min-h">
                    <div class="span12">
                        <div class="button-excel-export">

                        </div>
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                             <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Placas</th>
                                    <th>Modelo</th>
                                    <th>IMEI</th>
                                    <th>IP</th>
                                    <th>Último Reporte</th>
                                    <th>Dirección</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->datatTable as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['CLIENTE']; ?></td>
                                    <td><?php echo $items['PLACAS']; ?></td>
                                    <td><?php echo $items['MODELO']; ?></td>
                                    <td><?php echo $items['IMEI']; ?></td>
                                    <td><?php echo $items['IP']; ?></td>
                                    <td><?php echo $items['U_REPORTE']; ?></td>
                                    <td><?php echo $items['DIRECCION']; ?></td>
                                    <td class="text-center">
                                        <a href="/callcenter/rastreo/mapa?strInput=<?php echo $items['ID_ACTIVO']; ?>">
                                            <button class="btn btn-info"> <i class="icon-globe icon-white"></i>
                                            </button>
                                        </a>
                                    </td>
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /block -->
        </div>
    </div>         