<?php $this->headScript()->appendFile('/js/atn/validateSolicitudes.js') ?>  
<?php $disabled = (@$this->data['ID_ESTATUS']!=1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/atn/request/index" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                    <a href="javascript:backToMain()">
                        <i class="icon-circle-arrow-left fa-1"></i></a> Información de la Solicitud</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">

                    <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                        <li class="active"><a href="#tab" data-toggle="tab">Información General</a></li>
                        <li><a href="#tab2" data-toggle="tab">Log de Acciones</a></li>
                            <?php if(count($this->aProtocolo)>0):?>
                                <li><a href="#tab3" data-toggle="tab">Protocolo</a></li>
                            <?php endif;?>
                    </ul>

                    <div id="my-tab-content" class="tab-content bg-white">
                        <div class="tab-pane active" id="tab">
                            <?php if(@$this->errors['eIMEI']):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>El IMEI no se encuentra disponible</div>
                                </div>  
                            <?php endif;?> 
                            <?php if($disabled!='disabled'):?>
                            <form method="POST" action="/atn/request/getinfoemp" id="FormData" class="form-horizontal ">
                            <?php else:?>
                            <form id="FormData" class="form-horizontal ">
                            <?php endif;?>  
                                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                                <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                                <input type="hidden" id="bOperation" name="bOperation" value="accept" />
                                
                                <?php if($this->resultOp=='okRegister'): ?>
                                    <div class="alert alert-success">
                                        <button class="close" data-dismiss="alert"></button>
                                        Datos se almacenaron correctamente.
                                    </div>                        
                                <?php endif; ?>                 
                                    <fieldset>
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Fecha<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <input disabled readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['FECHA_CITA']; ?>">
                                                    </div>
                                                </div>              
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Horario<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputHorario" id="inputHorario"  disabled >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aHorarioCita;?>
                                                        </select>
                                                    </div>
                                                </div>                              
                                            </div>                                    
                                        </div>  
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">                                            
                                                    <label class="control-label">Tipo Cita<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputTipo" id="inputTipo"  disabled >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aTipos;?>
                                                        </select>
                                                    </div>
                                                </div>                                          
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">                                            
                                                    <label class="control-label">Tipo Equipo<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputTequipo" id="inputTequipo" disabled>
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aTequipos;?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>                                    
                                        </div> 

                                        <!--
                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Unidad<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputUnidad" id="inputUnidad" disabled onClick="getInfoUnit(this.value);" >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aUnidades;?>
                                                        </select>
                                                    </div>
                                                </div>                                                
                                            </div>
                                            <div class="span6">                                                
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputComment" id="inputComment" rows="5"  <?php echo $disabled;?> ><?php echo @$this->data['COMENTARIO']; ?></textarea>
                                                    </div>
                                                </div>                                           
                                            </div>                                    
                                        </div>
                                        -->  
                                        <div class="row row-margin-left25">    
                                            <div class="span12">
                                                <div class="control-group">
                                                    <label class="control-label">Dirección</label>
                                                    <div class="controls">
                                                        <input id="inputDir" name="inputDir" type="text" readonly value="<?php echo @$this->data['DIRECCION'];?>" class="form-control span10"/>
                                                    </div>
                                                </div>                                                
                                            </div>
                                        </div>                                           

                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Información Unidad</label>
                                                    <div class="controls">
                                                        <div id="infoUnit" name="infoUnit"><?php echo @$this->data['INFORMACION_UNIDAD']; ?></div>
                                                        <textarea name="inputInfo" id="inputInfo" rows="5" class="hide"><?php echo @$this->data['INFORMACION_UNIDAD']; ?></textarea>
                                                    </div>
                                                </div>                                                
                                            </div>
                                            <div class="span6">                                
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputComment" id="inputComment" rows="5" disabled ><?php echo @$this->data['COMENTARIO']; ?></textarea>
                                                    </div>
                                                </div>                                          
                                            </div>                                    
                                        </div> 


                                        <div class="row row-margin-left25"> 
                                            <div class="control-group">
                                                <span><b>Respuesta </b></span>
                                            </div>
                                        </div>
                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputrequest" id="inputrequest" rows="5"  <?php echo $disabled;?> ><?php echo @$this->data['request']; ?></textarea>
                                                    </div>
                                                </div>                                                
                                            </div>   
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label"></label>
                                                    <div class="controls">
                                                        <?php if(@$this->data['ID_ESTATUS']=="1" || @$this->data['ID_ESTATUS']=="4" ):?>
                                                            <button id="btnSaveOk"  type="submit" class="btn btn-primary">Aceptar Solicitud</button>
                                                            <button id="btnModify"  type="button" class="btn" onClick="javascript:modifyFields()">Modificar Información</button>
                                                            <button id="btnSave"    style="display:none;" type="submit" class="btn btn-primary">Guardar</button>
                                                            <button id="btnSaveCancel"   style="display:none;" onClick="javascript:cancelModify()" class="btn">Cancelar</button>
                                                        <?php elseif(@$this->data['ID_ESTATUS']=="6" ):?>
                                                            <button type="button" onClick="closeSol()" class="closeBtun btn btn-primary">Cerrar Solicitud</button>
                                                            <div id="closetxt" style="display:none;">
                                                                
                                                                 <div class="span12">
                                                                    <div class="control-group">
                                                                        <label class="control-label">Folio SAP<span class="required">*</span></label>
                                                                        <div class="controls">
                                                                            <input id="inputFolio" name="inputFolio" type="text" value="" class="form-control span10"/>    
                                                                        </div>
                                                                    </div>                                                
                                                                </div> 
                                                            </div>
                                                            <button id="btnCloseok" style="display:none;" type="submit" class="btn btn-primary">Guardar</button>
                                                        <?php endif;?>
                                                    </div>
                                                </div>                                                
                                            </div>                                       
                                        </div> 
                             
                                        <?php if($disabled!='disabled'):?>
                                        <div class="form-actions">
                                            <div class="pull-right">

                                                <!--<button type="submit" class="btn btn-primary">Aceptar Solicitud</button>
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                                <button type="button" class="btn" onClick="javascript:backToMain()">Cancel</button>-->
                                            </div>                                    
                                        </div>
                                        <?php endif;?>
                                </fieldset>
                            <?php if($disabled!='disabled'):?>
                            </form>
                            <?php endif;?>
                            <!-- END FORM-->      
                        </div>
                        <div class="tab-pane" id="tab2">
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    <tr>
                                        <th>Acción</th>
                                        <th>Descripción</th>
                                        <th>Hecho por</th>
                                        <th>Fecha Registrado</th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->logTable as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['ACTION']; ?></td>
                                        <td><?php echo $items['DESCRIPCION']; ?></td>
                                        <td><?php echo $items['ORIGEN']; ?></td>
                                        <td><?php echo $items['FECHA_CREADO']; ?></td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>                            
                        </div>  
                        <div class="tab-pane" id="tab3">
                            <?php if(count($this->aProtocolo)>0):?>
                                <?php $disabled = 'disabled';?>


                                    <div class="span12 no-margin-left">
                                        <div class="span6">
                                            <div class="control-group">
                                                <label class="control-label">Nombre o Razón Social<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputName" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['RAZON_SOCIAL']; ?>" >
                                                </div>
                                            </div>  
                                        </div>
                                        <div class="span6">
                                            <div class="control-group">
                                                <label class="control-label">RFC<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputRfc" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['RFC']; ?>" >
                                                </div>
                                            </div>  
                                        </div>                                      
                                    </div>  

                                    <div class="span12 no-margin-left">
                                        <div class="span12">
                                            <div class="control-group">
                                                <label class="control-label">Nombre Comercial o de Flota<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputFlota" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['NOMBRE_FLOTA']; ?>" >
                                                </div>
                                            </div>  
                                        </div>
                                    </div>

                                    <div class="span12 no-margin-left">
                                        <div class="span6">
                                            <div class="control-group">
                                                <label class="control-label">No. de Folio del Contrato<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputFolio" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['FOLIO_CONTRATO']; ?>" >
                                                </div>
                                            </div>  
                                        </div>
                                        <div class="span6">
                                            <div class="control-group">
                                                <label class="control-label">Tipo de Contrato<span class="required">*</span></label>
                                                <div class="controls">
                                                    <select <?php echo $disabled;?> class="span6 m-wrap"  autocomplete="off" name="inputContrato">
                                                        <?php echo $this->sTipos; ?>
                                                    </select>
                                                </div>
                                            </div>  
                                        </div>                                      
                                    </div>  

                                    <div class="span12 no-margin-left">
                                        <div class="span12">
                                            <div class="control-group">
                                                <label class="control-label">Asesor Comercial<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputAsesor" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['ASESOR_COMERCIAL']; ?>" >
                                                </div>
                                            </div>  
                                        </div>
                                    </div>  

                                    <div class="span12 no-margin-left">
                                        <div class="span12">
                                            <div class="control-group">
                                                <label class="control-label">Observaciones<span class="required">*</span></label>
                                                <div class="controls">
                                                    <input <?php echo $disabled;?> type="text" name="inputObservaciones" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->aProtocolo['OBSERVACIONES']; ?>" >
                                                </div>
                                            </div>  
                                        </div>
                                    </div>  

                                    <div class="span12 no-margin-left">
                                        <h4 style="text-align:center;">Personal Autorizado</h4>

                                        <table id="tableElements" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" > 
                                            <thead>
                                                <tr>
                                                    <th class="span1">Orden</th>
                                                    <th class="span2">Empresa</th>
                                                    <th class="span3">Nombre</th>
                                                    <th class="span2">Puesto</th>
                                                    <th class="span2">E-mail</th>        
                                                    <th class="span2">Avisar Prioridad Alta</th>
                                                    <th class="span2">Solicita ubicacion</th>                                                    
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php $control=0;?>                                     
                                                <?php foreach(@$this->aPersonas as $key => $items):?>
                                                    <tr>
                                                        <td>
                                                            <input name="aElements[<?php echo $control?>][id]" type="hidden" value="<?php echo $items['ID_CONTACTO_PROTOCOLO'];?>"/>
                                                            <input id="inputOp<?php echo $control?>" name="aElements[<?php echo $control?>][op]" type="hidden" value="up"/>
                                                            <input <?php echo $disabled;?> style="width:30px;" id="inputOrden<?php echo $control?>" name="aElements[<?php echo $control?>][orden]" type="text" class="span12"  value="<?php echo @$items['ORDEN'];?>"  autocomplete="off">                                                 
                                                        </td>
                                                        <td>
                                                            <input  <?php echo $disabled;?> class="span12" id="inputempreas<?php echo $control?>" name="aElements[<?php echo $control?>][empresa]"    type="text" name="" value="<?php echo $items['EMPRESA'];?>">
                                                        </td>
                                                        <td>  
                                                            <input <?php echo $disabled;?> class="span12"  id="inputnombre<?php echo $control?>" name="aElements[<?php echo $control?>][nombre]"  type="text" name="" value="<?php echo $items['NOMBRE_COMPLETO'];?>"></td>                                             
                                                        </td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="inputpuesto<?php echo $control?>" name="aElements[<?php echo $control?>][puesto]"   type="text" name="" value="<?php echo $items['PUESTO'];?>"></td>
                                                        </td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="inputemail<?php echo $control?>" name="aElements[<?php echo $control?>][email]"   type="text" name="" value="<?php echo $items['EMAIL'];?>"></td>
                                                        </td>
                                                        <td>
                                                            <select <?php echo $disabled;?> class="span12"  id="inputpriori<?php echo $control?>" name="aElements[<?php echo $control?>][ispriori]">
                                                                <?php echo $items['cboPalta'];?>
                                                            </select>
                                                        </td>
                                                        <td>
                                                            <select <?php echo $disabled;?> class="span12"  id="inputisposc<?php echo $control?>" name="aElements[<?php echo $control?>][isposc]">
                                                                <?php echo $items['cboPosic'];?>
                                                            </select>                                                   
                                                        </td>                                                        
                                                    </tr>
                                                    
                                                    <tr id="trOptions<?php echo $control?>" style="background-color:#f5f5f5;">                                                
                                                        <th></th>
                                                        <th class="span1">Clave de Identificación</th>
                                                        <th class="span1">Fecha Nac.</th>          
                                                        <th class="span1">Tel. Oficina</th>
                                                        <th class="span1">Nextel ID</th>
                                                        <th class="span1">Tel. Movil</th>
                                                        <th class="span1">Tel. 24 Hrs.</th>
                                                    </tr>
                                                    <tr id="trOptionsval<?php echo $control?>"> 
                                                        <td></td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12" id="inputclave<?php echo $control?>" name="aElements[<?php echo $control?>][clave]"    type="text" name="" value="<?php echo $items['CLAVE_IDENTIFICACION'];?>">
                                                        </td>
                                                        </td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12 cinputFecha" readonly id="inputfecnac<?php echo $control?>" name="aElements[<?php echo $control?>][fecnac]"   type="text" name="" value="<?php echo $items['FECHA_NACIMIENTO'];?>"></td>
                                                        </td>                                               
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="inputofna<?php echo $control?>" name="aElements[<?php echo $control?>][ofna]"   type="text" name="" value="<?php echo $items['TEL_OFICINA'];?>"></td>
                                                        </td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="inputnextid<?php echo $control?>" name="aElements[<?php echo $control?>][nextid]"   type="text" name="" value="<?php echo $items['NEXTEL_ID'];?>"></td>
                                                        </td>
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="inputtelmovil<?php echo $control?>" name="aElements[<?php echo $control?>][telmovil]"   type="text" name="" value="<?php echo $items['TEL_MOVIL'];?>"></td>
                                                        </td>                                               
                                                        <td>
                                                            <input <?php echo $disabled;?> class="span12"  id="input24hrs<?php echo $control?>" name="aElements[<?php echo $control?>][movil24hrs]"   type="text" name="" value="<?php echo $items['TEL_24HRS'];?>"></td>
                                                        </td>                                 
                                                    </tr>
                                                    <?php $control++;?>  
                                                <?php endforeach;?>
                                                <input type="hidden" id="inputCountElements" name="inputCountElements" value="<?php echo $control; ?>"/>                                                             
                                            </tbody>
                                        </table>
                                    </div>
                           
                                    <div class="control-group">
                                    </div>                                    

                            <?php endif;?>
                        </div>                   
                    </div>
                </div>                    
            </div>          
        </div>
    </div>
</div> 

<div class="modal fade hide modal-lg" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Activos Sin Asignar</h4>
      </div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>   