<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/js/atn/validateSolicitudes.js') ?>  
<?php $disabled = (@$this->data['ID_ESTATUS']!=1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/atn/request/index" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                    <a href="javascript:backToMain()">
                        <i class="icon-circle-arrow-left fa-1"></i></a> Información de la Solicitud</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">

                    <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                        <li class="active"><a href="#tab" data-toggle="tab">Información General</a></li>
                        <?php if(@$this->data['LATITUD']!="" && @$this->data['LONGITUD']!="" ):?>
                        <li><a href="#tab2" onClick="reDrawMap()" data-toggle="tab">Mapa Ubicación</a></li>
                        <?php endif;?>
                        <li><a href="#tab3" data-toggle="tab">Log de Acciones</a></li>
                    </ul>

                    <div id="my-tab-content" class="tab-content bg-white">
                        <div class="tab-pane active" id="tab">
                            <?php if(@$this->errors['eIMEI']):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>El IMEI no se encuentra disponible</div>
                                </div>  
                            <?php endif;?> 
                            <?php if($disabled!='disabled'):?>
                            <form method="POST" action="/atn/request/getinfo" id="FormData" class="form-horizontal ">
                            <?php else:?>
                            <form id="FormData" class="form-horizontal ">
                            <?php endif;?>  
                                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                                <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                                <input type="hidden" id="bOperation" name="bOperation" value="accept" />
                                
                                <?php if($this->resultOp=='okRegister'): ?>
                                    <div class="alert alert-success">
                                        <button class="close" data-dismiss="alert"></button>
                                        Datos se almacenaron correctamente.
                                    </div>                        
                                <?php endif; ?>                 
                                    <fieldset>
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Fecha<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <input disabled readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['FECHA_CITA']; ?>">
                                                    </div>
                                                </div>              
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Horario<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputHorario" id="inputHorario"  disabled >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aHorarioCita;?>
                                                        </select>
                                                    </div>
                                                </div>                              
                                            </div>                                    
                                        </div>  
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">                                            
                                                    <label class="control-label">Tipo Cita<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputTipo" id="inputTipo"  disabled >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aTipos;?>
                                                        </select>
                                                    </div>
                                                </div>                                          
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">                                            
                                                    <label class="control-label">Horario 2</label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputHorario2" id="inputHorario2"  disabled >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aHorarioCita2;?>
                                                        </select>
                                                    </div>
                                                </div>                          
                                            </div>                                    
                                        </div> 

                                        <?php if(@$this->data['LATITUD']!="" && @$this->data['LONGITUD']!="" ):?>
                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Lugar:</label>
                                                    <div class="controls">
                                                        <div ><?php echo @$this->data['DIRECCION_COMPLETA']; ?></div>
                                                    </div>
                                                </div>                                                
                                            </div>
                                            <div class="span6">                                                
                                                <div class="control-group">
                                                    <label class="control-label">Latitud/Longitud</label>
                                                    <div class="controls">
                                                        <div ><?php echo @$this->data['LATITUD']." , ".@$this->data['LONGITUD']; ?></div>
                                                    </div>
                                                </div>                                           
                                            </div>                                    
                                        </div>
                                        <?php endif;?>

                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Información Unidad</label>
                                                    <div class="controls">
                                                        <div id="infoUnit" name="infoUnit"><?php echo @$this->data['INFORMACION_UNIDAD']; ?></div>
                                                        <textarea name="inputInfo" id="inputInfo" rows="5" class="hide"><?php echo @$this->data['INFORMACION_UNIDAD']; ?></textarea>
                                                    </div>
                                                </div>                                                
                                            </div>
                                            <div class="span6">                                
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputComment" id="inputComment" rows="5" disabled ><?php echo @$this->data['COMENTARIO']; ?></textarea>
                                                    </div>
                                                </div>                                          
                                            </div>                                    
                                        </div> 


                                        <div class="row row-margin-left25"> 
                                            <div class="control-group">
                                                <span><b>Respuesta </b></span>
                                            </div>
                                        </div>
                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputRevision" id="inputRevision" rows="5"  <?php echo $disabled;?> ><?php echo @$this->data['REVISION']; ?></textarea>
                                                    </div>
                                                </div>                                                
                                            </div>   
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label"></label>
                                                    <div class="controls">
                                                        <?php if(@$this->data['ID_ESTATUS']=="1" || @$this->data['ID_ESTATUS']=="4" ):?>
                                                            <button id="btnSaveOk"  type="submit" class="btn btn-primary">Aceptar Solicitud</button>
                                                            <button id="btnModify"  type="button" class="btn" onClick="javascript:modifyFields()">Modificar Información</button>
                                                            <button id="btnSave"    style="display:none;" type="submit" class="btn btn-primary">Guardar</button>
                                                            <button id="btnSaveCancel"   style="display:none;" onClick="javascript:cancelModify()" class="btn">Cancelar</button>
                                                        <?php endif;?>
                                                    </div>
                                                </div>                                                
                                            </div>                                       
                                        </div> 
                             
                                        <?php if($disabled!='disabled'):?>
                                        <div class="form-actions">
                                            <div class="pull-right">
                                                <!--<button type="submit" class="btn btn-primary">Aceptar Solicitud</button>
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                                <button type="button" class="btn" onClick="javascript:backToMain()">Cancel</button>-->
                                            </div>                                    
                                        </div>
                                        <?php endif;?>
                                </fieldset>
                            <?php if($disabled!='disabled'):?>
                            </form>
                            <?php endif;?>
                            <!-- END FORM-->      
                        </div>
                        
                        <?php if(@$this->data['LATITUD']!="" && @$this->data['LONGITUD']!="" ):?>
                        <div class="tab-pane" id="tab2">
                            <input type="hidden" id="inputLatitud"  name="inputLatitud"  value="<?php echo @$this->data['LATITUD'];?>"  />
                            <input type="hidden" id="inputLontigud" name="inputLontigud" value="<?php echo @$this->data['LONGITUD'];?>" />
                            
                            <div class="row row-margin-left25">    
                                <div class="span6">
                                    <div class="control-group">
                                        <label class="control-label"><b>Lugar:</b></label>
                                        <div class="controls">
                                            <div ><?php echo @$this->data['DIRECCION_COMPLETA']; ?></div>
                                        </div>
                                    </div>                                                
                                </div>
                                <div class="span6">                                                
                                    <div class="control-group">
                                        <label class="control-label"><b>Latitud/Longitud</b></label>
                                        <div class="controls">
                                            <div ><?php echo @$this->data['LATITUD']." , ".@$this->data['LONGITUD']; ?></div>
                                        </div>
                                    </div>                                           
                                </div>                                    
                            </div>                            
                            <div id="Map" style="width:100%;height:350px;">

                            </div> 
                        </div>                        
                        <?php endif;?> 
                        <div class="tab-pane" id="tab3">
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    <tr>
                                        <th>Acción</th>
                                        <th>Descripción</th>
                                        <th>Hecho por</th>
                                        <th>Fecha Registrado</th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->logTable as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['ACTION']; ?></td>
                                        <td><?php echo $items['DESCRIPCION']; ?></td>
                                        <td><?php echo $items['ORIGEN']; ?></td>
                                        <td><?php echo $items['FECHA_CREADO']; ?></td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>                            
                        </div>                        
                    </div>
                </div>                    
            </div>          
        </div>
    </div>
</div> 

<div class="modal fade hide modal-lg" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Activos Sin Asignar</h4>
      </div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>   