<?php $this->headScript()->appendFile('/js/atn/validateSolicitudes.js') ?>  
<?php $disabled = (@$this->data['ID_ESTATUS']!=1) ? 'disabled':'';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/atn/request/index" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                    <a href="javascript:backToMain()">
                        <i class="icon-circle-arrow-left fa-1"></i></a>Información de la Solicitud</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <?php if(@$this->errors['eIMEI']):?>
                        <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                          <button type="button" class="close" data-dismiss="alert">×</button>
                          <h4>Error</h4>
                          <div>El IMEI no se encuentra disponible</div>
                        </div>  
                    <?php endif;?> 

                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    <tr>
                                        <th>Cliente</th>
                                        <th>Tipo</th>
                                        <th>Fecha Requerida</th>
                                        <th>Unidad</th>
                                        <th>Comentario</th>
                                    </tr>
                                </thead>
                                <tbody>               
                                    <tr class="odd gradeX">
                                        <td class="span4"><?php echo $this->data['N_CLIENTE']; ?></td>
                                        <td><?php echo $this->data['N_TIPO']; ?></td>
                                        <td class="span3"><?php echo $this->data['FECHA_CITA']; ?></td>
                                        <td><?php echo $this->data['UNIDAD']; ?></td>
                                        <td><?php echo $this->data['COMENTARIO']; ?></td>
                                    </tr>    
                                </tbody>
                            </table>                    
                   <!-- BEGIN FORM-->
                    <?php if($disabled!='disabled'):?>
                    <form method="POST" action="/atn/request/getinfo" id="FormData" class="form-horizontal ">
                    <?php else:?>
                    <form id="FormData" class="form-horizontal ">
                    <?php endif;?>  
                        <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                        <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
                        
                        <?php if($this->resultOp=='okRegister'): ?>
                            <div class="alert alert-success">
                                <button class="close" data-dismiss="alert"></button>
                                Datos se almacenaron correctamente.
                            </div>                        
                        <?php endif; ?>                 
                            <fieldset>
                                <div class="row row-margin-left25"> 
                                    <div class="control-group">
                                        <span><b>Respuesta </b></span>
                                    </div>
                                </div>

                                <div class="row row-margin-left25">    
                                    <div class="span5">
                                        <div class="control-group">
                                            <label class="control-label">Fecha<span class="required">*</span></label>
                                            <div class="controls">
                                                <input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['FECHA_CONFIRMADA']; ?>">
                                            </div>
                                        </div>              
                                    </div>

                                    <div class="span6">
                                        <div class="control-group">                                            
                                            <label class="control-label">Entre</label>
                                            <div class="controls">
                                                <input readonly id="inputTimeBegin" name="inputTimeBegin" data-required="1"  type="text" class="form-control span5" value="<?php echo @$this->data['HORA_INICIO']; ?>">
                                                Y
                                                <input readonly id="inputTimeEnd" name="inputTimeEnd" data-required="1"  type="text" class="form-control span5" value="<?php echo @$this->data['HORA_FIN']; ?>">
                                                Hrs.
                                            </div>
                                        </div>                          
                                    </div>                                                                     
                                </div>  

                                <div class="row row-margin-left25">    
                                    <div class="span5">
                                        <div class="control-group">
                                            <label class="control-label">Estatus<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="m-wrap span11" name="inputEstatus" id="inputEstatus" <?php echo $disabled;?> >
                                                    <option value="">Seleccionar una opción</option>
                                                    <?php echo $this->aEstatus;?>
                                                </select>                                                
                                            </div>
                                        </div>                                                
                                    </div> 
                                    <div class="span6">
                                        <div class="control-group">
                                            <label class="control-label">Comentarios<span class="required">*</span></label>
                                            <div class="controls">
                                                <textarea name="inputRevision" id="inputRevision" rows="5"  <?php echo $disabled;?> ><?php echo @$this->data['REVISION']; ?></textarea>
                                            </div>
                                        </div>                                                
                                    </div>   
                                </div> 
                     
                                <?php if($disabled!='disabled'):?>
                                <div class="form-actions">
                                    <div class="pull-right">
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <button type="button" class="btn" onClick="javascript:backToMain()">Cancel</button>
                                    </div>                                    
                                </div>
                                <?php endif;?>
                        </fieldset>
                    <?php if($disabled!='disabled'):?>
                    </form>
                    <?php endif;?>
                    <!-- END FORM-->                                                                
                </div>                    
                </div>          
            </div>
        </div>
</div> 

<div class="modal fade hide modal-lg" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Activos Sin Asignar</h4>
      </div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>   