<?php $this->headScript()->appendFile('/js/atn/tableSolicitudes.js') ?>  
<div class="row panel-data">

    <input id="hRefLinkEdit" type="hidden" value="/atn/request/getinfo?idRow=" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Solicitud de Citas</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                        <li class="active"><a href="#tab" data-toggle="tab">Solicitudes Pendientes</a></li>
                        <li><a href="#tab2" data-toggle="tab">Solicitudes Confirmadas</a></li>
                        <li><a href="#tab3" data-toggle="tab">Solicitudes Arrendadoras Pendientes</a></li>
                        <li><a href="#tab4" data-toggle="tab">Solicitudes Arrendadoras Confirmadas</a></li>
                    </ul>
                    <div id="my-tab-content" class="tab-content bg-white">
                        <div class="tab-pane active" id="tab">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    <tr>
                                        <th>Cliente</th>
                                        <th>Tipo</th>
                                        <th>Fecha Requerida</th>
                                        <th>Horario</th>
                                        <th>Unidad</th>
                                        <th>Estatus</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->dataTable as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['N_CLIENTE']; ?></td>
                                        <td><?php echo $items['N_TIPO']; ?></td>
                                        <td><?php echo $items['FECHA_CITA']; ?></td>
                                        <td><?php echo $items['N_HORARIO']; ?></td>
                                        <td><?php echo $items['N_UNIDAD']; ?></td>
                                        <td><?php echo $items['N_ESTATUS']; ?></td>
                                        <td class="text-center">
                                            <a href="/atn/request/getinfo?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        </td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane" id="tab2">
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable">
                                <thead>
                                    <tr>
                                        <th>Cliente</th>
                                        <th>Tipo</th>
                                        <th>Fecha Requerida</th>
                                        <th>Horario</th>
                                        <th>Unidad</th>
                                        <th>Estatus</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->dataTableOk as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['N_CLIENTE']; ?></td>
                                        <td><?php echo $items['N_TIPO']; ?></td>
                                        <td><?php echo $items['FECHA_CITA']; ?></td>
                                        <td><?php echo $items['N_HORARIO']; ?></td>
                                        <td><?php echo $items['N_UNIDAD']; ?></td>
                                        <td><?php echo $items['N_ESTATUS']; ?></td>
                                        <td class="text-center">
                                            <a href="/atn/request/getinfo?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        </td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div> 
                        <div class="tab-pane active" id="tab3">
                            <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Arrendadora</th>
                                        <th>Tipo</th>
                                        <th>Fecha</th>
                                        <th>Horario</th>
                                        <th>Unidad</th>
                                        <th>Lugar</th>                                        
                                        <th>Estatus</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->dataTableEmp as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['N_CLIENTE']; ?></td>
                                        <td><?php echo $items['N_TIPO']; ?></td>
                                        <td><?php echo $items['FECHA_CITA']; ?></td>
                                        <td><?php echo $items['N_HORARIO']; ?></td>
                                        <td><?php echo $items['N_UNIDAD']; ?></td>
                                        <td><?php echo $items['N_SUCURSAL'];?></td>
                                        <td><?php echo $items['N_ESTATUS']; ?></td>
                                        <td class="text-center">
                                            <a href="/atn/request/getinfoemp?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        </td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>
                        </div> 
                        <div class="tab-pane active" id="tab4">
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable">
                                <thead>
                                    <tr>
                                        <th>Arrendadora</th>
                                        <th>Tipo</th>
                                        <th>Fecha</th>
                                        <th>Horario</th>
                                        <th>Unidad</th>
                                        <th>Lugar</th>                                        
                                        <th>Estatus</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach($this->dataTableEmpOk as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['N_CLIENTE']; ?></td>
                                        <td><?php echo $items['N_TIPO']; ?></td>
                                        <td><?php echo $items['FECHA_CITA']; ?></td>
                                        <td><?php echo $items['N_HORARIO']; ?></td>
                                        <td><?php echo $items['N_UNIDAD']; ?></td>
                                        <td><?php echo $items['N_SUCURSAL'];?></td>
                                        <td><?php echo $items['N_ESTATUS']; ?></td>
                                        <td class="text-center">
                                            <a href="/atn/request/getinfoemp?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-primary"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        </td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>                                
                            </table>
                        </div>                                               
                    </div>                    
                </div>
            </div>
        </div>
        <!-- /block -->
    </div>
</div>   

<div id="modalConfirmDelete" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Atención!</h3>
    </div>
    <div class="modal-body">
        <p>¿Realmente desea eliminar este registro?</p>
    </div>
    <div class="modal-footer">
        <input type="hidden" id="inputDelete" value="-1"/>
        <a class="btn btn-primary" href="javascript:deleteRow();">Eliminar</a>
        <a data-dismiss="modal" class="btn" href="#">Cancelar</a>
    </div>
</div>    