<?php $this->headScript()->appendFile('/js/modules/leasing/validateSolicitudes.js') ?>  
<?php $disabled   = ((@$this->data['ID_ESTATUS']==1 || @$this->data['ID_ESTATUS']==4 ) || @$this->idToUpdate==-1) ? '' : 'disabled';?>
<?php $eDireccion = (@$this->idToUpdate==-1) ? 'readonly="readonly" ': '';?>
<?php $eCombos    = (@$this->idToUpdate==-1) ? 'disabled': '';?>
<div class="row panel-data">
    <input id="hRefLinkMain" type="hidden" value="/leasing/request/index" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                    <a href="javascript:backToMain()">
                        <i class="icon-circle-arrow-left fa-1"></i></a> Información de la Solicitud</div>
                        <div class="pull-right">
                            <span><?php echo (@$this->data['ID_ESTATUS']!="") ? 'Estatus: '.@$this->data['N_ESTATUS'] : '';?></span>
                        </div>        
            </div>
            <div class="block-content collapse in">
                <div id="divLoading" class="span12" style="display:none">
                    <img class="span3 offset4" src="/images/assets/loading.gif" alt="loading gif"/>
                </div>
                <div id="divContent" class="span12 no-margin-l">

                    <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                        <li class="active"><a href="#tab" data-toggle="tab">Información General</a></li>


                        <li><a href="#tab3" data-toggle="tab">Log de Acciones</a></li>
                        <div class="pull-right">
                            <?php if($this->dataUser['ID_TIPO_EMPRESA']==3 && $this->idToUpdate>0 && $this->data['ID_TIPO']==1):?>
                                <a href="/leasing/request/newprotocol?strSol=<?php echo $this->idToUpdate;?>">
                                    <button class="btn btn-block btn-success center-text" type="button"><i class="icon-plus-circle"></i> Ver Protocolo</button>
                                </a>
                            <?php endif;?>
                        </div>     
                    </ul>

                    <div id="my-tab-content" class="tab-content bg-white">
                        <div class="tab-pane active" id="tab">                            
                            <?php if(count($this->aClientes)==0):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>No se han registrado Clientes,agregue uno primero para solicitar una cita.</div>
                                </div>  
                            <?php endif;?> 
                            <?php if(@$this->errors['errorDate']):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>No se puede solicitar una cita en este horario, no hay tecnicos disponibles</div>
                                </div>                              
                            <?php endif;?>                        
                            <?php if(@$this->errors['errorDateInvalid']):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>Solo se pueden solicitar y/o modificar solicitudes con 12 hrs. de anticipación.</div>
                                </div>
                            <?php endif;?>  
                            <?php if(@$this->errors['errorUpdate']):?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>Ocurrio un problema al actualizar la información.</div>
                                </div>
                            <?php endif;?>  

                                                                                                            
                           <!-- BEGIN FORM-->
                            <form method="POST" action="/leasing/request/getinfo?catId=<?php echo $this->catId; ?>" id="FormData" class="form-horizontal ">
                                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                                <input type="hidden" id="catId"  name="catId" value="<?php echo $this->catId; ?>" />
                                <input type="hidden" id="bOperation" name="bOperation" value="<?php echo (@$this->data['ID_ESTATUS']==5) ? 'accept': '';?>" />
                                
                                <?php if($this->resultOp=='okRegister'): ?>
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        Datos se almacenaron correctamente.
                                    </div>    
                                <?php elseif($this->resultOp=='okUpdate'): ?>
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        Las Unidades se han actualizado correctamente.
                                    </div>                                                        
                                <?php endif; ?>

                                    <fieldset>
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Fecha<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['FECHA_CITA']; ?>">
                                                    </div>
                                                </div>              
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">                                            
                                                    <label class="control-label">Tipo Cita<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputTipo" id="inputTipo" <?php echo $disabled;?> >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aTipos;?>
                                                        </select>
                                                    </div>
                                                </div>                                                                                
                                            </div>                                    
                                        </div>  
                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Horario<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputHorario" id="inputHorario" <?php echo $disabled;?> >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aHorarioCita;?>
                                                        </select>
                                                    </div>
                                                </div>                                        
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Tipo Equipo<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inputTequipo" id="inputTequipo" <?php echo $disabled;?> >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aTequipos;?>
                                                        </select>
                                                    </div>
                                                </div>                                        
                                            </div>
                                        </div> 

                                        <div class="row row-margin-left25">                                       
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Cliente<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <select class="m-wrap" name="inpuClienteEmp" id="inpuClienteEmp" <?php echo $disabled;?> <?php echo (@$this->idToUpdate==-1) ? 'onChange="searchUnits(this.value)"': '';?> >
                                                            <option value="">Seleccionar una opción</option>
                                                            <?php echo $this->aClientes;?>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>                                             
                                            <div class="span6">
                                                                                                                  
                                            </div>                                             
                                        </div>                                         
                                        <div class="row row-margin-left25">    
                                            <div class="span6  <?php echo ($this->idToUpdate==-1)? '': 'text-center';?>">
                                                <?php if($this->idToUpdate==-1):?>
                                                <div class="control-group">
                                                    <label class="control-label">Lugar<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <div id="divLugares">
                                                            <select onChange="newdireccion(this.value);" class="m-wrap" name="inputPlace" id="inputPlace" <?php echo $disabled;?>  >
                                                                <option value="">Seleccionar una opción</option>
                                                                <?php echo $this->aSucursales;?>                                                                
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div> 
                                                <?php else:?>
                                                    <h4>Dirección Solicitud</h4>
                                                <?php endif;?>
                                                <div id="divDireNew" style="display:<?php echo ($this->catId>-1) ? 'block':'none' ;?>">
                                                    <div id="infoUnit"></div>
                                                    <div class="span12 no-margin-left">
                                                        <div class="control-group">
                                                            <label class="control-label">Calle<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputCalle" name="inputCalle" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['CALLE']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div> 
                                                        <div class="control-group">
                                                            <label class="control-label">Entre Calle<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputEntreCalles" name="inputEntreCalles" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['ENTRE_CALLES']; ?>" <?php echo $eDireccion;?>  >
                                                            </div>
                                                        </div>
                                                        <div class="control-group">
                                                            <label class="control-label">Referencias<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputRefs" name="inputRefs" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['REFERENCIAS']; ?>" <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>                                                        
                                                        <div class="control-group">
                                                            <label class="control-label">Colonia<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputColonia" name="inputColonia" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['COLONIA']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>  
                                                        <div class="control-group">
                                                            <label class="control-label">Municipio<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputMunicipio" name="inputMunicipio" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['MUNICIPIO']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>  
                                                        <div class="control-group">
                                                            <label class="control-label">Estado<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputEstado" name="inputEstado" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['ESTADO']; ?>" <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>
                                                        <div class="control-group">
                                                            <label class="control-label">CP<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputCP" name="inputCP" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['CP']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>  
                                                       <div class="control-group">
                                                            <label class="control-label">Contacto</label>
                                                            <div class="controls">
                                                                <input type="text" id="inputContacto" name="inputContacto" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['CONTACTO']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>   

                                                        <div class="control-group">
                                                            <label class="control-label">Tel. Contacto</label>
                                                            <div class="controls">
                                                                <input type="text" id="inputTelCont" name="inputTelCont" autocomplete="off" class="span12 m-wrap upperClass inputDir" value="<?php echo @$this->data['CONTACTO_TEL']; ?>"  <?php echo $eDireccion;?> >
                                                            </div>
                                                        </div>                                                         
                                                    </div>
                                                    <div class="span12 no-margin-left">
                                                        <div class="span6" id="divSaveDir" style="display:none">                                                            
                                                            <input id="chkSaveDir" name="chkSaveDir" type="checkbox" onChange="addNameDir();"/>
                                                            Deseo guardar esta direccion en mis Luages
                                                        </div>                                                                      
                                                    </div>
                                                    <div class="span12 no-margin-left" id="divNameDes" style="display:none;">
                                                        <div class="control-group">
                                                            <label class="control-label">Nombre<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input type="text" id="inputDescripcion" name="inputDescripcion" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->data['DESCRIPCION']; ?>" >
                                                            </div>
                                                        </div>  
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="span6 <?php echo ($this->idToUpdate==-1)? '': 'text-center';?>">
                                                <input type="hidden" id="txtIdCarSelected" name="txtIdCarSelected" value="<?php echo ($this->idToUpdate==-1) ? -1 : $this->data['ID_UNIDAD'];?>">                                                
                                                <?php if($this->idToUpdate==-1):?>
                                                <div class="control-group">                                                    
                                                    <label class="control-label">Unidad<span class="required">*</span></label>
                                                    <div class="controls">                                                        
                                                            <div id="divUnidad" class="span8">
                                                                <select class="m-wrap class="span4 m-wrap"" name="inputUnidad" id="inputUnidad" <?php echo $disabled;?> onChange="newCar(this.value);" >
                                                                    <option value="">Seleccionar una opción</option>
                                                                    <?php echo $this->aUnidades;?>
                                                                </select>                                                        
                                                            </div>
                                                    </div>                                           
                                                </div>
                                                <?php else:?>
                                                    <h4>Vehículo</h4>
                                                <?php endif;?>
                                                 <div id="divCarNew" style="display:<?php echo ($this->idToUpdate==-1) ? 'none':'block';?>">
                                                    <!--<div id="infoUnit"></div>-->
                                                    <div class="span12 no-margin-left">
                                                        <div class="control-group">
                                                            <label class="control-label">Marca<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <select class="span8 m-wrap inputCar" name="inputMarca" id="inputMarca"  <?php echo $eCombos;?>  onChange="getoptionsCbo('Modelo','modeloa',this.value,'','');">
                                                                    <option value="">Seleccionar una opción</option>
                                                                    <?php echo $this->aMarcas;?>
                                                                </select>
                                                            </div>
                                                        </div>  
                                                        <div class="control-group">
                                                            <label class="control-label">Modelo<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <div id="divModelo">
                                                                    <select class="span8 m-wrap inputCar" name="inputModelo" id="inputModelo"  <?php echo $eCombos;?>  >
                                                                        <option value="">Seleccionar una opción</option>
                                                                        <?php echo $this->aModelos;?>
                                                                    </select>
                                                                </div>
                                                            </div>
                                                        </div>                              
                                                        <div class="control-group">
                                                            <label class="control-label">Color<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <select class="span8 m-wrap inputCar" id="inputColor" name="inputColor"  <?php echo $eCombos;?> >
                                                                    <?php echo $this->sColores; ?>
                                                                </select>
                                                            </div>
                                                        </div>  
                                                        <div class="control-group">
                                                            <label class="control-label">Año<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <select class="span8 m-wrap inputCar" id="inputAnio" name="inputAnio"  <?php echo $eCombos;?>  >
                                                                    <?php echo $this->sAnios; ?>
                                                                </select>
                                                            </div>
                                                        </div>                              
                                                        <div class="control-group">
                                                            <label class="control-label">Placas<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input name="inputPlacas" id="inputPlacas" type="text" class="span8 m-wrap upperClass inputCar" value="<?php echo @$this->aInfoUnit['PLACAS']; ?>"  <?php echo $eDireccion;?>  >
                                                            </div>
                                                        </div>
                                                        <div class="control-group">
                                                            <label class="control-label">No. serie<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input name="inputIden" id="inputIden" type="text" class="span8 m-wrap upperClass inputCar" value="<?php echo @$this->aInfoUnit['IDENTIFICADOR']; ?>"  <?php echo $eDireccion;?>  >
                                                            </div>
                                                        </div>     
                                                        <div class="control-group">
                                                            <label class="control-label">No. Contrato<span class="required">*</span></label>
                                                            <div class="controls">
                                                                <input name="inputIden2" id="inputIden2" type="text" class="span8 m-wrap upperClass inputCar" value="<?php echo @$this->aInfoUnit['IDENTIFICADOR_2']; ?>"  <?php echo $eDireccion;?>  >
                                                            </div>
                                                        </div>  
                                                    </div>
                                                </div> 
                                        </div>
                                        <div class="row row-margin-left25">    
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Comentarios<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <textarea name="inputComment" id="inputComment" rows="5"  <?php echo $disabled;?> ><?php echo @$this->data['COMENTARIO']; ?></textarea>
                                                    </div>
                                                </div>                                                                                              
                                            </div>
                                            <div class="span6">
                                            </div>                                    
                                        </div>

                                        <div class="row row-margin-left25">
                                            <div class="span6">
                                          
                                            </div>
                                            <div class="span6">

                                            </div>                                    
                                        </div>
                                        <div class="form-actions">
                                            <div class="pull-right">
                                                <?php if($disabled!='disabled'):?>
                                                    <button type="submit" class="btn btn-primary">Guardar</button>
                                                    <button type="button" class="btn" onClick="javascript:backToMain()">Cancelar</button>
                                                <?php endif;?>                                        
                                            </div>                                    
                                        </div>
                                </fieldset>
                            </form>
                        </div>
                        <div class="tab-pane" id="tab3">
                           <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                                <thead>
                                    <tr>
                                        <th>Acción</th>
                                        <th>Descripción</th>
                                        <th>Hecho por</th>
                                        <th>Fecha Registrado</th>
                                    </tr>
                                </thead>
                                <tbody>                                
                                    <?php foreach(@$this->logTable as $key => $items): ?>  
                                    <tr class="odd gradeX">
                                        <td><?php echo $items['ACTION']; ?></td>
                                        <td><?php echo $items['DESCRIPCION']; ?></td>
                                        <td><?php echo $items['ORIGEN']; ?></td>
                                        <td><?php echo $items['FECHA_CREADO']; ?></td>
                                    </tr>    
                                    <?php endforeach;?>
                                </tbody>
                            </table>                            
                        </div> 
                    </div>        
                </div>                    
            </div>          
        </div>
    </div>
</div>

<div class="modal fade hide modal-lg" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Unidad</h4>
      </div>
      <div class="modal-form i-body">  
        <img id="loader" class="col-xs-offset-4" src="/images/assets/images/loading.gif" alt="loading gif"/>            
        <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>   