<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>  
<?php $this->headScript()->appendFile('/js/atn/mainDetalle.js') ?>     
<div class="panel-data">
    <input id="hRefLinkEdit" type="hidden" value="/leasing/request/getinfo?idRow=" />
    <div class="container">
        <div class="block">
            <ul id="tabs" class="nav nav-tabs bg-white" data-tabs="tabs">
                <li class="active"><a href="#tab" data-toggle="tab">Información General</a></li>
                <li><a href="#tab3" data-toggle="tab">Log de Acciones</a></li>   
            </ul>

            <div id="my-tab-content" class="tab-content bg-white">
                <div class="tab-pane active" id="tab">
                    <fieldset>
                        <div class="row-fluid">                                       
                            <div class="span3">
                                <div class="control-group">
                                    <label class="control-label"><b>Fecha:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['FECHA_CITA']; ?></span>
                                    </div>
                                </div>              
                            </div>
                            <div class="span3">
                                <div class="control-group">                                            
                                    <label class="control-label"><b>Horario:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['N_HORARIO']; ?></span>
                                    </div>
                                </div>                                                                                
                            </div>  
                            <div class="span3">
                                <div class="control-group">                                            
                                    <label class="control-label"><b>Tipo Cita:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['N_TIPO']; ?></span>
                                    </div>
                                </div>                                                                                
                            </div>
                            <div class="span3">
                                <div class="control-group">                                            
                                    <label class="control-label"><b>Estatus:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['N_ESTATUS']; ?></span>
                                    </div>
                                </div>                                                                                
                            </div>                            
                        </div> 
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label"><b>Cliente:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['N_CLIENTE']; ?></span>
                                    </div>
                                </div>              
                            </div>                             
                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label"><b>Tipo de Equipo:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['N_EQUIPO']; ?></span>
                                    </div>
                                </div>              
                            </div>                            
                        </div>
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">                                            
                                    <label class="control-label"><b>Direccion:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['DIRECCION']; ?></span>
                                    </div>
                                </div>                                                                                
                            </div>  
                            <div class="span5">
                                <div class="control-group">                                            
                                    <label class="control-label"><b>Vehículo:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['INFORMACION_UNIDAD']; ?></span>
                                    </div>
                                </div>                                                                                
                            </div>                                                               
                        </div> 
                        <div class="row-fluid">
                            <div class="span6">
                                <div class="control-group">
                                    <label class="control-label"><b>Comentarios:</b></label>
                                    <div class="controls">
                                        <span><?php echo @$this->aDataInfo['COMENTARIO']; ?></span>
                                    </div>
                                </div>              
                            </div>   
                            <div class="span6">
                                
                            </div>                          
                        </div>       

                        <div class="row-fluid text-center">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label"></label>
                                    <div class="controls">
                                        <?php if(@$this->aDataInfo['ID_ESTATUS']=="5" || @$this->aDataInfo['ID_ESTATUS']=="9"):?>
                                            <button id="btnSaveOk"  type="button" class="btn btn-primary" onClick="javascript:parent.acceptSol(<?php echo $this->aDataInfo['ID_SOLICITUD']; ?>)">Aceptar Solicitud</button>
                                            <button id="btnModify"  type="button" class="btn" onClick="javascript:parent.goToEdit(<?php echo $this->aDataInfo['ID_SOLICITUD']; ?>)">Modificar Información</button>
                                        <?php endif;?>
                                    </div>
                                </div>                                                
                            </div>                                       
                        </div>                                                                  
                    </fieldset>
                </div>
                <div class="tab-pane" id="tab3">
                   <table id="dataTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered dataTable" >
                        <thead>
                            <tr>
                                <th>Acción</th>
                                <th>Descripción</th>
                                <th>Hecho por</th>
                                <th>Fecha Registrado</th>
                            </tr>
                        </thead>
                        <tbody>                                
                            <?php foreach(@$this->logTable as $key => $items): ?>  
                            <tr class="odd gradeX">
                                <td><?php echo $items['ACTION']; ?></td>
                                <td><?php echo $items['DESCRIPCION']; ?></td>
                                <td><?php echo $items['ORIGEN']; ?></td>
                                <td><?php echo $items['FECHA_CREADO']; ?></td>
                            </tr>    
                            <?php endforeach;?>
                        </tbody>
                    </table>                            
                </div>                     
            </div>
        </div>
    </div>
</div>
