<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>   
<?php $this->headScript()->appendFile('/js/modules/leasing/jsTableSolicitudes.js') ?>  
<div class="row panel-data">

    <input id="hRefLinkEdit" type="hidden" value="/leasing/request/getinfo?idRow=" />
    <div class="span12">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">Solicitud de Citas</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">
                    <div class="table-toolbar">
                      <div class="btn-group">
                         <a href="/leasing/request/getinfo?catId=-1"><button class="btn btn-success"> Solicitar Cita <i class="icon-plus icon-white"></i></button></a>
                      </div>
                    </div>  
                    <div class="row customform bg-white">
                        <form method="POST" action="/leasing/request/index" id="FormData" class="form-horizontal formcustom">
                            <input type="hidden" name="optReg" id="optReg" value="search" />
                            <fieldset>                             
                                <div class="row row-margin-left25">    
                                    <div class="span5">
                                        <div class="control-group">
                                            <label class="control-label">Fecha Inicio<span class="required">*</span></label>
                                            <div class="controls">
                                                <input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputFechaIn']; ?>">
                                            </div>
                                        </div>              
                                    </div>
                                    <div class="span5">
                                        <div class="control-group">
                                            <label class="control-label">Fecha Fin<span class="required">*</span></label>
                                            <div class="controls">
                                                <input readonly type="text" id="inputFechaFin" name="inputFechaFin" class="m-wrap" value="<?php echo (@$this->data['inputFechaFin']); ?>">                          
                                            </div>
                                        </div>                          
                                    </div>  
                                    <div class="span2">                                                                        
                                    <!--
                                        <div class="">
                                            <button type="submit" class="btn btn-primary">Buscar</button>
                                        </div>
                                    -->
                                    </div>                                                                                    
                                </div>  

                                <div class="row row-margin-left25">
                                    <div class="span5">
                                        <div class="control-group">
                                            <label class="control-label">Estatus<span class="required">*</span></label>
                                            <div class="controls">
                                                <select class="chzn-select" id="cboTypeSearch" name="cboTypeSearch" onChange="getReport()">
                                                    <option value="">Seleccionar una opción</option>
                                                    <?php echo $this->aTypeSearchs;?>
                                                </select>
                                            </div>
                                        </div>                                                       
                                    </div>
                                    <div class="span5">

                                    </div>
                                    <div class="span2">
                                        <div class="">
                                            <button type="submit" class="btn btn-primary">Buscar</button>
                                        </div>
                                    </div>                                       
                                </div>
                            </fieldset>                                                 
                        </form>                      
                    </div> 
                    <div class="span11">
                        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                            <thead>
                                <tr>
                                    <th>Cliente</th>
                                    <th>Tipo</th>                                        
                                    <th>Fecha - Horario</th>
                                    <th>Tipo Equipo</th>
                                    <th>Unidad</th>                                        
                                    <th>Lugar</th>                                        
                                    <th>Estatus</th>
                                    <th style="width:100px;"></th>
                                </tr>
                            </thead>
                            <tbody>                                
                                <?php foreach($this->dataTable as $key => $items): ?>  
                                <tr class="odd gradeX">
                                    <td><?php echo $items['N_EMP_CLIENTE']; ?></td>
                                    <td><?php echo $items['N_TIPO']; ?></td>
                                    <td><?php echo $items['FECHA_CITA']; ?><br>
                                        <?php echo $items['N_HORARIO']; ?></td>
                                    <td><?php echo $items['N_TEQUIPO']; ?></td>
                                    <td><?php echo $items['N_UNIDAD']; ?></td>
                                    <td><?php echo $items['N_SUCURSAL'];?></td>
                                    <td><?php echo $items['N_ESTATUS']; ?></td>
                                    <td class="text-center">
                                        <a href="javascript:showDetail(<?php echo $items['ID_SOLICITUD']; ?>)"><button class="btn btn-primary btn-mini"> <i class="icon-eye-open icon-white"></i></button></a>   
                                        <?php if($items['EDITABLE']==1 && $items['ON_TIME']==1): ?>
                                            <?php if($items['ID_ESTATUS']=='1' || $items['ID_ESTATUS']=='4'):?>
                                                <a href="/leasing/request/getinfo?catId=<?php echo $items['ID_SOLICITUD']; ?>"><button class="btn btn-info btn-mini"> <i class="icon-edit icon-white"></i></button></a>   
                                                <a href="javascript:confirmCancelSol('<?php echo $items['ID_SOLICITUD']; ?>')"><button class="btn btn-danger btn-mini"> <i class="icon-remove-sign icon-white"></i></button></a>
                                            <?php endif;?>
                                        <?php endif;?> 
                                    </td>
                                </tr>    
                                <?php endforeach;?>
                            </tbody>
                        </table>  
                    </span>
                </div>
            </div>
        </div>               
    </div>
</div>   

<div id="modalConfirmDelete" class="modal hide">
    <div class="modal-header">
        <button data-dismiss="modal" class="close" type="button">&times;</button>
        <h3>Atención!</h3>
    </div>
    <div class="modal-body">
        <p>¿Realmente desea eliminar este registro?</p>
        Comentarios:
        <textarea id="inCancelComent" name="inCancelComent"></textarea>
    </div>
    <div class="modal-footer">
        <input type="hidden" id="inputCancelSol" value="-1"/>
        <a class="btn btn-primary" href="javascript:cancelSolicitud();">Eliminar</a>
        <a data-dismiss="modal" class="btn" href="#">Cancelar</a>
    </div>
</div>    

<div class="modal fade hide modal-lg" id="myModalinfoVis" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" ></h4>
        </div>
      <div class="modal-form i-body">    
        <img id="loader" class="offset4" src="/images/assets/loading.gif" alt="loading gif" style="display:none;"/>
        <iframe class="hmodal500" id="iFrameDetCita" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>  