<?php $this->headScript()->appendFile('/js/modules/leasing/jsValidateProtocols.js') ?>   
<?php $disabled = ($this->myOpte>0) ? 'disabled':'';?>
<div class="row panel-data formcustom">
    <input id="hRefLinkMain" type="hidden" value="/leasing/request/getinfo?catId=<?php echo $this->strSol; ?>" />
	<div class="">
		<!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                	<?php if($this->myOpte>0):?>
					<a href="javascript:backToMainModule()">
						<i class="icon-circle-arrow-left fa-1"></i></a>
					<?php endif;?>
                	Protocolo</div>
            </div>
            <div class="block-content collapse in">
                <div class="span12">                	
                	<?php if($this->myOpte==0):?>
					<form method="POST" action="/leasing/request/newprotocol" id="FormData" class="form-horizontal ">
		                <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->myOpte>0) ? 'update': 'new';?>" />
		                <input type="hidden" name="strSol" value="<?php echo $this->strSol; ?>" />
		                <input type="hidden" name="catId" value="<?php echo $this->catId; ?>" />
		            <?php endif;?>
		                <?php if($this->resultOp=='okRegister'): ?>
		                    <div class="alert alert-success">
		                        <button class="close" data-dismiss="alert"></button>
		                        Datos se almacenaron correctamente.
		                    </div>                
		                <?php endif; ?>	  
	                	<fieldset>

            				<div class="span12 no-margin-left">
		                		<div class="span6">
		                			<div class="control-group">
										<label class="control-label">Nombre o Razón Social<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputName" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['RAZON_SOCIAL']; ?>" >
										</div>
									</div>	
		                		</div>
								<div class="span6">
		                			<div class="control-group">
										<label class="control-label">RFC<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputRfc" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['RFC']; ?>" >
										</div>
									</div>	
		                		</div>				                		
		                	</div>	

	                		<div class="span12 no-margin-left">
		                		<div class="span12">
									<div class="control-group">
										<label class="control-label">Nombre Comercial o de Flota<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputFlota" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['NOMBRE_FLOTA']; ?>" >
										</div>
									</div>	
		                		</div>
		                	</div>

            				<div class="span12 no-margin-left">
		                		<div class="span6">
		                			<div class="control-group">
										<label class="control-label">No. de Folio del Contrato<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputFolio" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['FOLIO_CONTRATO']; ?>" >
										</div>
									</div>	
		                		</div>
								<div class="span6">
		                			<div class="control-group">
										<label class="control-label">Tipo de Contrato<span class="required">*</span></label>
										<div class="controls">
											<select <?php echo $disabled;?> class="span6 m-wrap"  autocomplete="off" name="inputContrato">
												<?php echo $this->sTipos; ?>
											</select>
										</div>
									</div>	
		                		</div>				                		
		                	</div>	

            				<div class="span12 no-margin-left">
		                		<div class="span12">
									<div class="control-group">
										<label class="control-label">Asesor Comercial<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputAsesor" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['ASESOR_COMERCIAL']; ?>" >
										</div>
									</div>	
		                		</div>
		                	</div>	

            				<div class="span12 no-margin-left">
		                		<div class="span12">
									<div class="control-group">
										<label class="control-label">Observaciones<span class="required">*</span></label>
										<div class="controls">
											<input <?php echo $disabled;?> type="text" name="inputObservaciones" autocomplete="off" class="span12 m-wrap upperClass" value="<?php echo @$this->dataProt['OBSERVACIONES']; ?>" >
										</div>
									</div>	
		                		</div>
		                	</div>	

							<div class="span12 no-margin-left">
								<h4 style="text-align:center;">Personal Autorizado</h4>

								<table id="tableElements" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" > 
                                    <thead>
                                        <tr>
                                        	<th class="span1">Orden</th>
                                        	<th class="span2">Empresa</th>
                                            <th class="span3">Nombre</th>
                                            <th class="span2">Puesto</th>
                                            <th class="span2">E-mail</th>        
                                            <th class="span2">Avisar Prioridad Alta</th>
                                            <th class="span2">Solicita ubicacion</th>
                                            <th class="span1"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    	<?php $control=0;?>                                    	
                                    	<?php foreach(@$this->aPersonas as $key => $items):?>
                                    		<tr>
                                    			<td>
                                                    <input name="aElements[<?php echo $control?>][id]" type="hidden" value="<?php echo $items['ID_CONTACTO_PROTOCOLO'];?>"/>
                                                    <input id="inputOp<?php echo $control?>" name="aElements[<?php echo $control?>][op]" type="hidden" value="up"/>
                                                    <input <?php echo $disabled;?> style="width:30px;" id="inputOrden<?php echo $control?>" name="aElements[<?php echo $control?>][orden]" type="text" class="span12"  value="<?php echo @$items['ORDEN'];?>"  autocomplete="off">                                                 
                                                </td>
                                                <td>
                                    				<input  <?php echo $disabled;?> class="span12" id="inputempreas<?php echo $control?>" name="aElements[<?php echo $control?>][empresa]"    type="text" name="" value="<?php echo $items['EMPRESA'];?>">
                                    			</td>
                                    			<td>  
                                    			    <input <?php echo $disabled;?> class="span12"  id="inputnombre<?php echo $control?>" name="aElements[<?php echo $control?>][nombre]"  type="text" name="" value="<?php echo $items['NOMBRE_COMPLETO'];?>"></td>                              				
                                    			</td>
                                    			<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="inputpuesto<?php echo $control?>" name="aElements[<?php echo $control?>][puesto]"   type="text" name="" value="<?php echo $items['PUESTO'];?>"></td>
                                    			</td>
                                    			<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="inputemail<?php echo $control?>" name="aElements[<?php echo $control?>][email]"   type="text" name="" value="<?php echo $items['EMAIL'];?>"></td>
                                    			</td>
                                    			<td>
                                    				<select <?php echo $disabled;?> class="span12"  id="inputpriori<?php echo $control?>" name="aElements[<?php echo $control?>][ispriori]">
                                                        <?php echo $items['cboPalta'];?>
                                                    </select>
                                    			</td>
                                    			<td>
                                    				<select <?php echo $disabled;?> class="span12"  id="inputisposc<?php echo $control?>" name="aElements[<?php echo $control?>][isposc]">
                                                        <?php echo $items['cboPosic'];?>
                                                    </select>                                    				
                                    			</td>
                                    			<td>
                                    				<?php if($this->myOpte==0):?>
                                                    <button onClick="deleteFieldForm(this,<?php echo $control?>);return false;" class="btn"><i class="icon-remove-sign"></i></button>
                                                	<?php endif;?>
                                                </td> 
                                    		</tr>
                                    		
                                    		<tr id="trOptions<?php echo $control?>" style="background-color:#f5f5f5;">                                                
                                    			<th></th>
                                    			<th class="span1">Clave de Identificación</th>
                                    			<th class="span1">Fecha Nac.</th>          
                                    			<th class="span1">Tel. Oficina</th>
	                                            <th class="span1">Nextel ID</th>
	                                            <th class="span1">Tel. Movil</th>
	                                            <th class="span1">Tel. 24 Hrs.</th>
                                    		</tr>
											<tr id="trOptionsval<?php echo $control?>"> 
												<td></td>
												<td>
                                    				<input <?php echo $disabled;?> class="span12" id="inputclave<?php echo $control?>" name="aElements[<?php echo $control?>][clave]"    type="text" name="" value="<?php echo $items['CLAVE_IDENTIFICACION'];?>">
                                    			</td>
												</td>
                                    			<td>
                                    				<input <?php echo $disabled;?> class="span12 cinputFecha" readonly id="inputfecnac<?php echo $control?>" name="aElements[<?php echo $control?>][fecnac]"   type="text" name="" value="<?php echo $items['FECHA_NACIMIENTO'];?>"></td>
                                    			</td>												
	                                        	<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="inputofna<?php echo $control?>" name="aElements[<?php echo $control?>][ofna]"   type="text" name="" value="<?php echo $items['TEL_OFICINA'];?>"></td>
                                    			</td>
                                    			<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="inputnextid<?php echo $control?>" name="aElements[<?php echo $control?>][nextid]"   type="text" name="" value="<?php echo $items['NEXTEL_ID'];?>"></td>
                                    			</td>
												<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="inputtelmovil<?php echo $control?>" name="aElements[<?php echo $control?>][telmovil]"   type="text" name="" value="<?php echo $items['TEL_MOVIL'];?>"></td>
                                    			</td>                                    			
                                    			<td>
                                    				<input <?php echo $disabled;?> class="span12"  id="input24hrs<?php echo $control?>" name="aElements[<?php echo $control?>][movil24hrs]"   type="text" name="" value="<?php echo $items['TEL_24HRS'];?>"></td>
                                    			</td>                                 
	                                        </tr>
                                    		<?php $control++;?>  
                                    	<?php endforeach;?>
                                    	<?php if($this->myOpte==0):?>
                                    	<tr>
	                                        <td colspan="9">
	                                            <div class="block">
	                                                <button class="btn btn-block btn-success center-text" type="button" onClick="addFieldForm();"><i class="icon-plus-circle"></i> Agregar Elemento</button>                                            
	                                            </div>                                    
	                                        </td>    
                                    	</tr> 
                                    	<?php endif;?>
                                    	<input type="hidden" id="inputCountElements" name="inputCountElements" value="<?php echo $control; ?>"/>                                                             
                                    </tbody>
                                </table>
							</div>
	               
							<div class="control-group">
							</div>
							<?php if($this->myOpte==0):?>

							<div class="form-actions text-right">
								<!--<a href="/leasing/branches/index">
									<button type="button" class="btn">Cancelar</button>
								</a>-->
								<button type="submit" class="btn btn-primary">Guardar</button>
							</div>
							<?php endif;?>
						</fieldset>
					<?php if($this->myOpte==0):?>
					</form>							
					<?php endif;?>								
				</div>
		    </div>
		</div>
	</div>
</div>  


<div id="divSelectStatus" class="hide">
    <?php echo $this->aPosition;?>
</div>