<?php $this->headScript()->appendFile('/js/forms/jsValidateForms.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>

<div class="panel-data">
    <input id="hRefLinkMain" type="hidden" value="/forms/main/index" />
    <div class="span12 no-margin-l">
        <!-- block -->
        <div class="block">
            <div class="navbar navbar-inner block-header">
                <div class="muted pull-left">
                    <a href="javascript:backToMainModule()">
                        <i class="icon-circle-arrow-left fa-1"></i></a>Información del Formulario</div>
            </div>
            <div class="block-content collapse in">
            <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                <li class="<?php echo (@$this->eventAction) ? '':'active';?>"><a href="#init" data-toggle="tab">Información</a></li>
                <?php if($this->idToUpdate>0):?>
                    <li class="<?php echo (@$this->eventAction) ? 'active':'';?>"><a href="#detalle" data-toggle="tab">Elementos</a></li>
                <?php endif;?>              
            </ul>

            <div id="my-tab-content" class="tab-content bg-white">
                <div class="tab-pane  <?php echo (@$this->eventAction) ? '':'active';?> " id="init">  

                        <div class="span12">
                            <?php if(@$this->errors['eIMEI']):?>
                                <!--<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>El IMEI no se encuentra disponible</div>
                                </div>  -->                            
                            <?php endif;?>
                            <?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
                                <div id="divpErrorLogin" class="alert alert-error" style="display:block;">
                                  <button type="button" class="close" data-dismiss="alert">×</button>
                                  <h4>Error</h4>
                                  <div>Usted no tiene permiso para ver esta información</div>
                                </div>
                            <?php else:?>   

                            <!-- BEGIN FORM-->
                            <?php if($disabled!='disabled'):?>
                            <form method="POST" action="/forms/main/getinfo" id="FormData" class="form-horizontal ">
                            <?php endif;?>  
                                <input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                                <input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />                                
                                <?php if($this->resultOp=='okRegister'): ?>
                                    <div class="alert alert-success">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        Datos se almacenaron correctamente.
                                    </div>                        
                                <?php endif; ?>                                  
                                    <fieldset>
                                        <div class="span12">
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label for="inputTipo" class="control-label"><span class="required">*</span> Tipo Formulario</label>
                                                    <div class="controls">
                                                        <select class="span6 m-wrap" name="inputTipo" id="inputTipo" <?php echo $disabled;?> onChange="oncChangeType(this.value)">
                                                            <option value=""> Seleccione una opción</option>
                                                            <?php echo $this->aTipoForm;?>
                                                        </select>                                                
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label class="control-label">Icono<span class="required">*</span></label>
                                                    <div class="controls">
                                                        <input type="hidden" id="inputIdAssign" name="inputIdAssign" value="<?php echo @$this->aDataInfo['ID_ICONO'];?>"/>
                                                        <?php if(@$this->aDataInfo['ASIGNADO']=='0' || @$this->idToUpdate==-1):?>
                                                            <img name="inputSearch" id="inputSearch" style="width:50px;display:none;" src=""/>
                                                            <button id="btnSearch" class="btn" ><i class="icon-search"></i></button>
                                                        <?php else:?>
                                                            <img  name="inputAsign"  style="width:30px;" src="/images/icons/<?php echo @$this->aDataInfo['ASIGNADO']; ?>"/>
                                                            <button id="btnDelRel" class="btn btn-danger" ><i class="icon-remove-sign icon-white"></i></button>
                                                        <?php endif;?>                                      
                                                    </div>
                                                </div>  
                                            </div>
                                        </div>
                                        
                                        <div class="span12 no-margin-l">
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label for="inputTitulo" class="control-label"><span class="required">*</span> Titulo</label>
                                                    <div class="controls">
                                                        <input id="inputTitulo" name="inputTitulo" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['TITULO'];?>"  autocomplete="off">
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="span6">
                                                <div id="divControlCliente" class="control-group" style="display:<?php echo (@$this->aDataInfo['TIPO_FORMULARIO'] == 'M') ? 'block': 'none'; ?>;">
                                                    <label for="inputOrden" class="control-label"> Cliente</label>
                                                    <div class="controls">
                                                        <select id="inputCliente" name="inputCliente" class="">
                                                            <option value="-1">Seleccione una opción</option>
                                                            <?php echo $this->aClientesSap ;?>
                                                        </select>
                                                    </div>
                                                </div>  
                                            </div>                                        
                                        </div>


                                        <div class="span12 no-margin-l">
                                            <div class="span6">
                                                <div class="control-group">
                                                    <label for="inputDescripcion" class="control-label"><span class="required">*</span> Descripción</label>
                                                    <div class="controls">
                                                        <input id="inputDescripcion" name="inputDescripcion" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['N_DESC'];?>"  autocomplete="off">
                                                    </div>
                                                </div>  
                                            </div>
                                                

                                            <div class="span6">
                                                <div id="divControlNumber" class="control-group" style="display:<?php echo (@$this->aDataInfo['TIPO_FORMULARIO'] == 'M') ? 'block': 'none'; ?>;">
                                                    <label for="inputOrden" class="control-label"> # Caracteres</label>
                                                    <div class="controls">
                                                        <input id="inputLength" name="inputLength" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['CARACTERES_CAMPO'];?>"  autocomplete="off">
                                                    </div>
                                                </div>  
                                            </div>                                        
                                        </div>





                                        

                                        <div class="control-group">
                                            <label for="inputOrden" class="control-label"><span class="required">*</span> Orden</label>
                                            <div class="controls">
                                                <input id="inputOrden" name="inputOrden" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['ORDEN'];?>"  autocomplete="off">
                                            </div>
                                        </div>         

                                        <div class="control-group">
                                            <label for="inputIdOvision" class="control-label"><span class="required">*</span> Id Ovision</label>
                                            <div class="controls">
                                                <input id="inputIdOvision" name="inputIdOvision" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['ID_OVISION'];?>"  autocomplete="off">
                                            </div>
                                        </div>                                                 

                                        <div class="control-group">
                                            <label for="inputEstatus" class="control-label"><span class="required">*</span> Estatus</label>
                                            <div class="controls">
                                                <select id="inputEstatus" name="inputEstatus" class="">
                                                    <?php echo $this->aEstatus ;?>
                                                </select>
                                            </div>
                                        </div>
                                        <!--
                                        <div class="control-group">
                                            <label for="inputLocate" class="control-label"><span class="required">*</span> Localización</label>
                                            <div class="controls">
                                                <select id="inputLocate" name="inputLocate" class="">
                                                    <?php echo $this->aLocal ;?>
                                                </select>
                                            </div>
                                        </div>                            

                                        <div class="control-group">
                                            <label for="inputPhotos" class="control-label"><span class="required">*</span> Fotos Extras</label>
                                            <div class="controls">
                                                <select id="inputPhotos" name="inputPhotos" class="">
                                                    <?php echo $this->aFotos ;?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="inputQrs" class="control-label"><span class="required">*</span> QR Extras</label>
                                            <div class="controls">
                                                <select id="inputQrs" name="inputQrs" class="">
                                                    <?php echo $this->aQrs ;?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="control-group">
                                            <label for="inputFirma" class="control-label"><span class="required">*</span>Firmas Extras</label>
                                            <div class="controls">
                                                <select id="inputFirma" name="inputFirma" class="">
                                                    <?php echo $this->aFirms ;?>
                                                </select>
                                            </div>
                                        </div>  
                                        -->

                                        <?php if($disabled!='disabled'):?>
                                        <div class="form-actions">
                                            <button type="submit" class="btn btn-primary">Guardar</button>
                                            <button type="button" class="btn" onClick="javascript:backToMain()">Cancel</button>
                                        </div>
                                        <?php endif;?>
                                </fieldset>
                            <?php if($disabled!='disabled'):?>
                            </form>
                            <?php endif;?>
                            <!-- END FORM-->                                                                
                            <?php endif;?>
                        </div>
                    </div>
                    <div class="tab-pane <?php echo (@$this->eventAction) ? 'active':'';?>" id="detalle">                   


                        <?php $control=0;?>
                        <!--<div class="row-min-h300" id="divContenedor">-->
                            <form id="FormData3" class="form-horizontal" role="form" method="POST" action="/forms/main/getinfo">
                                <input type="hidden" id="catId" name="catId"  value="<?php echo $this->catId; ?>" id="catId" />
                                <input type="hidden" id="optReg" name="optReg" value="updateElements" />
                                <input type="hidden" name="strTabSelected" value="2" />
                                <table id="tableElements" class="table table-striped ">     
                                    <thead>
                                        <tr>
                                            <th class="span1">Id</th>
                                            <th class="span1">Orden</th>
                                            <th class="span4">Tipo</th>
                                            <th class="span4">Descripción</th>                                    
                                            <th class="span2">Estatus</th>
                                            <th class="span2">Requerido</th>
                                            <th class="span2">Validación Local</th>
                                            <th class="span2"></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach(@$this->aElements as $key => $items):?>
                                            <tr>
                                                <td>
                                                    <?php echo $items['ID_ELEMENTO'];?>
                                                </td>
                                                <td>
                                                    <input name="aElements[<?php echo $control?>][id]" type="hidden" value="<?php echo $items['ID_ELEMENTO'];?>"/>
                                                    <input id="inputOp<?php echo $control?>" name="aElements[<?php echo $control?>][op]" type="hidden" value="up"/>
                                                    <input style="width:30px;" id="inputElement<?php echo $control?>" name="aElements[<?php echo $control?>][orden]" type="text" class="span12"  value="<?php echo @$items['ORDEN'];?>"  autocomplete="off">                                                 
                                                </td>
                                                <td>
                                                    <select class="span12"  id="inputTipo<?php echo $control?>" name="aElements[<?php echo $control?>][tipo]" onChange="onChangeSelect(this.value,<?php echo $control;?>);">
                                                        <?php echo $items['cboTipo'];?>
                                                    </select>
                                                </td>                                        
                                                <td>
                                                    <input id="inputDesc<?php echo $control?>" name="aElements[<?php echo $control?>][desc]" type="text" class="span12"  value="<?php echo @$items['N_ELEMENTO'];?>"  autocomplete="off">                                                 
                                                </td>
                                                <td> 
                                                    <select class="span12"  id="inputStat<?php echo $control?>" name="aElements[<?php echo $control?>][status]">
                                                        <?php echo $items['cboStatus'];?>
                                                    </select>
                                                </td>
                                                <td> 
                                                    <select class="span12"  id="inputReq<?php echo $control?>" name="aElements[<?php echo $control?>][requerido]">
                                                        <?php echo $items['cboReq'];?>
                                                    </select>
                                                </td>
                                                <td> 
                                                    <select class="span12"  id="inputVal<?php echo $control?>" name="aElements[<?php echo $control?>][validacion]">
                                                        <?php echo $items['cboVal'];?>
                                                    </select>
                                                </td>  
                                                <td>
                                                    <div class="span12 no-margin-l">
                                                        <div class="btn-group">
                                                            <?php $biconSet = ($items['VALORES_CONFIG']!="" || $items['DEPENDE']!="" || $items['ESPERA']!="" ) ? 'icon-chevron-up': 'icon-chevron-down';?>
                                                            <button onClick="showCloseOptions(<?php echo $control; ?>);return false;" class="btn"> <i  id="spanOptions<?php echo $control; ?>" class="<?php echo $biconSet;?>"></i></button>
                                                            <button onClick="deleteFieldForm(this,<?php echo $control?>);return false;" class="btn"><i class="icon-remove-sign"></i></button>
                                                        </div>
                                                    </div> 
                                                </td>                                                                     
                                            </tr>
                                            
                                            <?php $bVisible = ($items['VALORES_CONFIG']!="" || $items['DEPENDE']!="" || $items['ESPERA']!="" ) ? '': 'display:none;';?>                                            
                                            <tr id="trOptions<?php echo $control?>" style="background-color:#f5f5f5;<?php echo $bVisible;?>">                                                
                                                <td colspan="6">
                                                    <?php $bVisOpts = ($items['VALORES_CONFIG']!="") ? '': 'display:none;';?>
                                                    <div id="divOptions<?php echo $control;?>" style="">
                                                        <textarea id="inputOps<?php echo $control?>" name="aElements[<?php echo $control?>][options]" rows="4" class="span12 no-padding"><?php echo $items['VALORES_CONFIG'];?></textarea>
                                                        Opciones (Delimitados por comas <i>ej:uno,dos,tres</i>):
                                                    </div>
                                                </td>
                                                <td colspan="3">
                                                    <table>
                                                        <tr>
                                                            <td class="text-right" style="">
                                                                Depende de (# elemento)
                                                            </td>
                                                            <td>
                                                                <input class="span12"  id="inputDepend<?php echo $control?>" name="aElements[<?php echo $control?>][depend]" type="text" class="input-inline form-control col-xs-8 no-padding"  value="<?php echo @$items['DEPENDE'];?>"  autocomplete="off"/>
                                                            </td>                                                            
                                                        </tr>
                                                        <tr>
                                                            <td class="text-right" style="">
                                                                Cuando sea
                                                            </td>
                                                            <td colspan="2">
                                                                <input  class="span12"  id="inputCuando<?php echo $control?>" name="aElements[<?php echo $control?>][when]" type="text" class="input-inline form-control col-xs-8 no-padding"  value="<?php echo @$items['ESPERA'];?>"  autocomplete="off"/>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>    
                                            <?php $control++;?>                          
                                        <?php endforeach;?>
                                    </tbody>
                                    <tr>
                                        <td colspan="8">
                                            <div class="block">
                                                <button class="btn btn-block btn-success center-text" type="button" onClick="addFieldForm();"><i class="icon-plus-circle"></i> Agregar Elemento</button>                                            
                                            </div>                                    
                                        </td>    
                                    </tr>                            
                                </table>
                                <div class="form-group  margin-t5px">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <div class="pull-right">
                                            <button type="submit" class="btn btn-info">Guardar Cambios</button>
                                            <button type="button" class="btn default" onClick="location.href='<?php echo $this->moduleInfo['SCRIPT']; ?>';">Cancelar</button>   
                                        </div>
                                    </div>
                                </div> 
                                <input type="hidden" id="inputCountElements" name="inputCountElements" value="<?php echo $control; ?>"/>                                                             
                            </form>
                    </div>                      
                </div>          
            </div>
        </div>
    </div>  
</div> 

<div id="divSelectStatus" class="hide">
    <?php echo $this->selectStatus;?>
</div>

<div id="divSelectOptions" class="hide">
    <?php echo $this->selectOptions;?>
</div>

<div id="divSelectTypes" class="hide">
    <?php echo $this->selectTypes;?>
</div>



<div class="modal fade hide modal-lg" id="MyModalSearch" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" >Buscar Iconos</h4>
      </div>
      <div class="modal-form i-body">             
        <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
      </div>
    </div>
  </div>
</div>   