<?php $this->headScript()->appendFile('/js/main/searchActivos.js') ?>  	
    <!-- block -->
    <div class="block">
        <div class="block-content collapse in">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                    <thead>
                        <tr>
                        	<th>Clave Almacen</th>
                            <th>Nombre</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach($this->dataTable as $key => $items): ?>  
                        <tr class="odd gradeX">
                            <td><?php echo $items['CVE_ALMACEN']; ?></td>
                            <td><?php echo $items['NOMBRE']; ?></td>
                            <td class="text-center">                                
                                <a href="javascript:parent.assignValue('<?php echo $items['NOMBRE']; ?>','<?php echo $items['CVE_ALMACEN'];?>',2)"><button class="btn btn-primary"> <i class="icon-circle-arrow-down icon-white"></i></button></a>
                            </td>
                        </tr>    
                        <?php endforeach;?>                                             
                    </tbody>
                </table>
        </div>
    </div>
    <!-- /block -->